
package acs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// DeleteAccountBinding invokes the acs.DeleteAccountBinding API synchronously
// api document: https://help.aliyun.com/api/acs/deleteaccountbinding.html
func (client *Client) DeleteAccountBinding(request *DeleteAccountBindingRequest) (response *DeleteAccountBindingResponse, err error) {
response = CreateDeleteAccountBindingResponse()
err = client.DoAction(request, response)
return
}

// DeleteAccountBindingWithChan invokes the acs.DeleteAccountBinding API asynchronously
// api document: https://help.aliyun.com/api/acs/deleteaccountbinding.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) DeleteAccountBindingWithChan(request *DeleteAccountBindingRequest) (<-chan *DeleteAccountBindingResponse, <-chan error) {
responseChan := make(chan *DeleteAccountBindingResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.DeleteAccountBinding(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// DeleteAccountBindingWithCallback invokes the acs.DeleteAccountBinding API asynchronously
// api document: https://help.aliyun.com/api/acs/deleteaccountbinding.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) DeleteAccountBindingWithCallback(request *DeleteAccountBindingRequest, callback func(response *DeleteAccountBindingResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *DeleteAccountBindingResponse
var err error
defer close(result)
response, err = client.DeleteAccountBinding(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// DeleteAccountBindingRequest is the request struct for api DeleteAccountBinding
type DeleteAccountBindingRequest struct {
*requests.RoaRequest
                    Product     string `position:"Path" name:"Product"`
                    AliyunUid     string `position:"Path" name:"AliyunUid"`
                    Accept     string `position:"Header" name:"Accept"`
}


// DeleteAccountBindingResponse is the response struct for api DeleteAccountBinding
type DeleteAccountBindingResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
}

// CreateDeleteAccountBindingRequest creates a request to invoke DeleteAccountBinding API
func CreateDeleteAccountBindingRequest() (request *DeleteAccountBindingRequest) {
request = &DeleteAccountBindingRequest{
RoaRequest: &requests.RoaRequest{},
}
request.InitWithApiInfo("Acs", "2015-01-01", "DeleteAccountBinding", "/AccountBinding/[Product]/[AliyunUid]", "", "")
request.Method = requests.DELETE
return
}

// CreateDeleteAccountBindingResponse creates a response to parse from DeleteAccountBinding response
func CreateDeleteAccountBindingResponse() (response *DeleteAccountBindingResponse) {
response = &DeleteAccountBindingResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


