
package acs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// GetGatedLaunchApi invokes the acs.GetGatedLaunchApi API synchronously
// api document: https://help.aliyun.com/api/acs/getgatedlaunchapi.html
func (client *Client) GetGatedLaunchApi(request *GetGatedLaunchApiRequest) (response *GetGatedLaunchApiResponse, err error) {
response = CreateGetGatedLaunchApiResponse()
err = client.DoAction(request, response)
return
}

// GetGatedLaunchApiWithChan invokes the acs.GetGatedLaunchApi API asynchronously
// api document: https://help.aliyun.com/api/acs/getgatedlaunchapi.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) GetGatedLaunchApiWithChan(request *GetGatedLaunchApiRequest) (<-chan *GetGatedLaunchApiResponse, <-chan error) {
responseChan := make(chan *GetGatedLaunchApiResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.GetGatedLaunchApi(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// GetGatedLaunchApiWithCallback invokes the acs.GetGatedLaunchApi API asynchronously
// api document: https://help.aliyun.com/api/acs/getgatedlaunchapi.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) GetGatedLaunchApiWithCallback(request *GetGatedLaunchApiRequest, callback func(response *GetGatedLaunchApiResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *GetGatedLaunchApiResponse
var err error
defer close(result)
response, err = client.GetGatedLaunchApi(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// GetGatedLaunchApiRequest is the request struct for api GetGatedLaunchApi
type GetGatedLaunchApiRequest struct {
*requests.RoaRequest
                    ApiName     string `position:"Path" name:"ApiName"`
                    ProductName     string `position:"Path" name:"ProductName"`
                    VersionName     string `position:"Path" name:"VersionName"`
                    Accept     string `position:"Header" name:"Accept"`
}


// GetGatedLaunchApiResponse is the response struct for api GetGatedLaunchApi
type GetGatedLaunchApiResponse struct {
*responses.BaseResponse
            Name     string `json:"name" xml:"name"`
            Status     string `json:"status" xml:"status"`
            Product     string `json:"product" xml:"product"`
            Version     string `json:"version" xml:"version"`
            Visibility     string `json:"visibility" xml:"visibility"`
            ControlPolicy     string `json:"controlPolicy" xml:"controlPolicy"`
            AuthType     string `json:"authType" xml:"authType"`
            ResultMapping     string `json:"ResultMapping" xml:"ResultMapping"`
            GatedLaunch     string `json:"gatedLaunch" xml:"gatedLaunch"`
            GatedLaunchPolicy     string `json:"gatedLaunchPolicy" xml:"gatedLaunchPolicy"`
            IsvProtocol IsvProtocol  `json:"IsvProtocol" xml:"IsvProtocol"`
            IspProtocol IspProtocol  `json:"IspProtocol" xml:"IspProtocol"`
            ErrorMapping ErrorMapping  `json:"ErrorMapping" xml:"ErrorMapping"`
            FlowControl FlowControl  `json:"FlowControl" xml:"FlowControl"`
                    Parameters ParametersInGetGatedLaunchApi `json:"Parameters" xml:"Parameters"`
}

// CreateGetGatedLaunchApiRequest creates a request to invoke GetGatedLaunchApi API
func CreateGetGatedLaunchApiRequest() (request *GetGatedLaunchApiRequest) {
request = &GetGatedLaunchApiRequest{
RoaRequest: &requests.RoaRequest{},
}
request.InitWithApiInfo("Acs", "2015-01-01", "GetGatedLaunchApi", "/GatedLaunch/[ProductName]/[VersionName]/[ApiName]", "", "")
request.Method = requests.GET
return
}

// CreateGetGatedLaunchApiResponse creates a response to parse from GetGatedLaunchApi response
func CreateGetGatedLaunchApiResponse() (response *GetGatedLaunchApiResponse) {
response = &GetGatedLaunchApiResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


