
package acs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// GetGatedLaunchPolicyByProduct invokes the acs.GetGatedLaunchPolicyByProduct API synchronously
// api document: https://help.aliyun.com/api/acs/getgatedlaunchpolicybyproduct.html
func (client *Client) GetGatedLaunchPolicyByProduct(request *GetGatedLaunchPolicyByProductRequest) (response *GetGatedLaunchPolicyByProductResponse, err error) {
response = CreateGetGatedLaunchPolicyByProductResponse()
err = client.DoAction(request, response)
return
}

// GetGatedLaunchPolicyByProductWithChan invokes the acs.GetGatedLaunchPolicyByProduct API asynchronously
// api document: https://help.aliyun.com/api/acs/getgatedlaunchpolicybyproduct.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) GetGatedLaunchPolicyByProductWithChan(request *GetGatedLaunchPolicyByProductRequest) (<-chan *GetGatedLaunchPolicyByProductResponse, <-chan error) {
responseChan := make(chan *GetGatedLaunchPolicyByProductResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.GetGatedLaunchPolicyByProduct(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// GetGatedLaunchPolicyByProductWithCallback invokes the acs.GetGatedLaunchPolicyByProduct API asynchronously
// api document: https://help.aliyun.com/api/acs/getgatedlaunchpolicybyproduct.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) GetGatedLaunchPolicyByProductWithCallback(request *GetGatedLaunchPolicyByProductRequest, callback func(response *GetGatedLaunchPolicyByProductResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *GetGatedLaunchPolicyByProductResponse
var err error
defer close(result)
response, err = client.GetGatedLaunchPolicyByProduct(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// GetGatedLaunchPolicyByProductRequest is the request struct for api GetGatedLaunchPolicyByProduct
type GetGatedLaunchPolicyByProductRequest struct {
*requests.RoaRequest
                    Product     string `position:"Path" name:"Product"`
                    Accept     string `position:"Header" name:"Accept"`
}


// GetGatedLaunchPolicyByProductResponse is the response struct for api GetGatedLaunchPolicyByProduct
type GetGatedLaunchPolicyByProductResponse struct {
*responses.BaseResponse
                GatedLaunchPolicys GatedLaunchPolicys `json:"GatedLaunchPolicys" xml:"GatedLaunchPolicys"`
}

// CreateGetGatedLaunchPolicyByProductRequest creates a request to invoke GetGatedLaunchPolicyByProduct API
func CreateGetGatedLaunchPolicyByProductRequest() (request *GetGatedLaunchPolicyByProductRequest) {
request = &GetGatedLaunchPolicyByProductRequest{
RoaRequest: &requests.RoaRequest{},
}
request.InitWithApiInfo("Acs", "2015-01-01", "GetGatedLaunchPolicyByProduct", "/GatedLaunchPolicy/[Product]", "", "")
request.Method = requests.GET
return
}

// CreateGetGatedLaunchPolicyByProductResponse creates a response to parse from GetGatedLaunchPolicyByProduct response
func CreateGetGatedLaunchPolicyByProductResponse() (response *GetGatedLaunchPolicyByProductResponse) {
response = &GetGatedLaunchPolicyByProductResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


