
package acs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// GetFlowSpecialAPI invokes the acs.GetFlowSpecialAPI API synchronously
// api document: https://help.aliyun.com/api/acs/getflowspecialapi.html
func (client *Client) GetFlowSpecialAPI(request *GetFlowSpecialAPIRequest) (response *GetFlowSpecialAPIResponse, err error) {
response = CreateGetFlowSpecialAPIResponse()
err = client.DoAction(request, response)
return
}

// GetFlowSpecialAPIWithChan invokes the acs.GetFlowSpecialAPI API asynchronously
// api document: https://help.aliyun.com/api/acs/getflowspecialapi.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) GetFlowSpecialAPIWithChan(request *GetFlowSpecialAPIRequest) (<-chan *GetFlowSpecialAPIResponse, <-chan error) {
responseChan := make(chan *GetFlowSpecialAPIResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.GetFlowSpecialAPI(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// GetFlowSpecialAPIWithCallback invokes the acs.GetFlowSpecialAPI API asynchronously
// api document: https://help.aliyun.com/api/acs/getflowspecialapi.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) GetFlowSpecialAPIWithCallback(request *GetFlowSpecialAPIRequest, callback func(response *GetFlowSpecialAPIResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *GetFlowSpecialAPIResponse
var err error
defer close(result)
response, err = client.GetFlowSpecialAPI(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// GetFlowSpecialAPIRequest is the request struct for api GetFlowSpecialAPI
type GetFlowSpecialAPIRequest struct {
*requests.RoaRequest
                    Product     string `position:"Path" name:"Product"`
                    Name     string `position:"Query" name:"Name"`
                    Accept     string `position:"Header" name:"Accept"`
}


// GetFlowSpecialAPIResponse is the response struct for api GetFlowSpecialAPI
type GetFlowSpecialAPIResponse struct {
*responses.BaseResponse
            Product     string `json:"product" xml:"product"`
            Name     string `json:"name" xml:"name"`
                    Apis ApisInGetFlowSpecialAPI `json:"Apis" xml:"Apis"`
}

// CreateGetFlowSpecialAPIRequest creates a request to invoke GetFlowSpecialAPI API
func CreateGetFlowSpecialAPIRequest() (request *GetFlowSpecialAPIRequest) {
request = &GetFlowSpecialAPIRequest{
RoaRequest: &requests.RoaRequest{},
}
request.InitWithApiInfo("Acs", "2015-01-01", "GetFlowSpecialAPI", "/GetFlowSpecialAPI/[Product]/[Name]", "", "")
request.Method = requests.GET
return
}

// CreateGetFlowSpecialAPIResponse creates a response to parse from GetFlowSpecialAPI response
func CreateGetFlowSpecialAPIResponse() (response *GetFlowSpecialAPIResponse) {
response = &GetFlowSpecialAPIResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


