
package acs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// GetDocTag invokes the acs.GetDocTag API synchronously
// api document: https://help.aliyun.com/api/acs/getdoctag.html
func (client *Client) GetDocTag(request *GetDocTagRequest) (response *GetDocTagResponse, err error) {
response = CreateGetDocTagResponse()
err = client.DoAction(request, response)
return
}

// GetDocTagWithChan invokes the acs.GetDocTag API asynchronously
// api document: https://help.aliyun.com/api/acs/getdoctag.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) GetDocTagWithChan(request *GetDocTagRequest) (<-chan *GetDocTagResponse, <-chan error) {
responseChan := make(chan *GetDocTagResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.GetDocTag(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// GetDocTagWithCallback invokes the acs.GetDocTag API asynchronously
// api document: https://help.aliyun.com/api/acs/getdoctag.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) GetDocTagWithCallback(request *GetDocTagRequest, callback func(response *GetDocTagResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *GetDocTagResponse
var err error
defer close(result)
response, err = client.GetDocTag(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// GetDocTagRequest is the request struct for api GetDocTag
type GetDocTagRequest struct {
*requests.RoaRequest
                    Product     string `position:"Path" name:"Product"`
                    TagId     string `position:"Path" name:"TagId"`
                    Language     string `position:"Path" name:"Language"`
                    Accept     string `position:"Header" name:"Accept"`
}


// GetDocTagResponse is the response struct for api GetDocTag
type GetDocTagResponse struct {
*responses.BaseResponse
            Product     string `json:"product" xml:"product"`
            TagId     string `json:"tagId" xml:"tagId"`
            Name     string `json:"name" xml:"name"`
            Type     string `json:"type" xml:"type"`
            Language     string `json:"language" xml:"language"`
            Index     string `json:"index" xml:"index"`
}

// CreateGetDocTagRequest creates a request to invoke GetDocTag API
func CreateGetDocTagRequest() (request *GetDocTagRequest) {
request = &GetDocTagRequest{
RoaRequest: &requests.RoaRequest{},
}
request.InitWithApiInfo("Acs", "2015-01-01", "GetDocTag", "/DocTag/[Product]/[TagId]/[Language]", "", "")
request.Method = requests.GET
return
}

// CreateGetDocTagResponse creates a response to parse from GetDocTag response
func CreateGetDocTagResponse() (response *GetDocTagResponse) {
response = &GetDocTagResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


