
package acs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// GetSecretKey invokes the acs.GetSecretKey API synchronously
// api document: https://help.aliyun.com/api/acs/getsecretkey.html
func (client *Client) GetSecretKey(request *GetSecretKeyRequest) (response *GetSecretKeyResponse, err error) {
response = CreateGetSecretKeyResponse()
err = client.DoAction(request, response)
return
}

// GetSecretKeyWithChan invokes the acs.GetSecretKey API asynchronously
// api document: https://help.aliyun.com/api/acs/getsecretkey.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) GetSecretKeyWithChan(request *GetSecretKeyRequest) (<-chan *GetSecretKeyResponse, <-chan error) {
responseChan := make(chan *GetSecretKeyResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.GetSecretKey(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// GetSecretKeyWithCallback invokes the acs.GetSecretKey API asynchronously
// api document: https://help.aliyun.com/api/acs/getsecretkey.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) GetSecretKeyWithCallback(request *GetSecretKeyRequest, callback func(response *GetSecretKeyResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *GetSecretKeyResponse
var err error
defer close(result)
response, err = client.GetSecretKey(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// GetSecretKeyRequest is the request struct for api GetSecretKey
type GetSecretKeyRequest struct {
*requests.RoaRequest
                    Product     string `position:"Path" name:"Product"`
                    Accept     string `position:"Header" name:"Accept"`
}


// GetSecretKeyResponse is the response struct for api GetSecretKey
type GetSecretKeyResponse struct {
*responses.BaseResponse
                    SecretKeys SecretKeys `json:"SecretKeys" xml:"SecretKeys"`
}

// CreateGetSecretKeyRequest creates a request to invoke GetSecretKey API
func CreateGetSecretKeyRequest() (request *GetSecretKeyRequest) {
request = &GetSecretKeyRequest{
RoaRequest: &requests.RoaRequest{},
}
request.InitWithApiInfo("Acs", "2015-01-01", "GetSecretKey", "/SecretKey/[Product]", "", "")
request.Method = requests.GET
return
}

// CreateGetSecretKeyResponse creates a response to parse from GetSecretKey response
func CreateGetSecretKeyResponse() (response *GetSecretKeyResponse) {
response = &GetSecretKeyResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


