
package acs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// GetFlowSpecialByProduct invokes the acs.GetFlowSpecialByProduct API synchronously
// api document: https://help.aliyun.com/api/acs/getflowspecialbyproduct.html
func (client *Client) GetFlowSpecialByProduct(request *GetFlowSpecialByProductRequest) (response *GetFlowSpecialByProductResponse, err error) {
response = CreateGetFlowSpecialByProductResponse()
err = client.DoAction(request, response)
return
}

// GetFlowSpecialByProductWithChan invokes the acs.GetFlowSpecialByProduct API asynchronously
// api document: https://help.aliyun.com/api/acs/getflowspecialbyproduct.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) GetFlowSpecialByProductWithChan(request *GetFlowSpecialByProductRequest) (<-chan *GetFlowSpecialByProductResponse, <-chan error) {
responseChan := make(chan *GetFlowSpecialByProductResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.GetFlowSpecialByProduct(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// GetFlowSpecialByProductWithCallback invokes the acs.GetFlowSpecialByProduct API asynchronously
// api document: https://help.aliyun.com/api/acs/getflowspecialbyproduct.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) GetFlowSpecialByProductWithCallback(request *GetFlowSpecialByProductRequest, callback func(response *GetFlowSpecialByProductResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *GetFlowSpecialByProductResponse
var err error
defer close(result)
response, err = client.GetFlowSpecialByProduct(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// GetFlowSpecialByProductRequest is the request struct for api GetFlowSpecialByProduct
type GetFlowSpecialByProductRequest struct {
*requests.RoaRequest
                    Product     string `position:"Path" name:"Product"`
                    Accept     string `position:"Header" name:"Accept"`
}


// GetFlowSpecialByProductResponse is the response struct for api GetFlowSpecialByProduct
type GetFlowSpecialByProductResponse struct {
*responses.BaseResponse
                FlowSpecials FlowSpecialsInGetFlowSpecialByProduct `json:"FlowSpecials" xml:"FlowSpecials"`
}

// CreateGetFlowSpecialByProductRequest creates a request to invoke GetFlowSpecialByProduct API
func CreateGetFlowSpecialByProductRequest() (request *GetFlowSpecialByProductRequest) {
request = &GetFlowSpecialByProductRequest{
RoaRequest: &requests.RoaRequest{},
}
request.InitWithApiInfo("Acs", "2015-01-01", "GetFlowSpecialByProduct", "/FlowSpecial/[Product]", "", "")
request.Method = requests.GET
return
}

// CreateGetFlowSpecialByProductResponse creates a response to parse from GetFlowSpecialByProduct response
func CreateGetFlowSpecialByProductResponse() (response *GetFlowSpecialByProductResponse) {
response = &GetFlowSpecialByProductResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


