
package acs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// PutDocTag invokes the acs.PutDocTag API synchronously
// api document: https://help.aliyun.com/api/acs/putdoctag.html
func (client *Client) PutDocTag(request *PutDocTagRequest) (response *PutDocTagResponse, err error) {
response = CreatePutDocTagResponse()
err = client.DoAction(request, response)
return
}

// PutDocTagWithChan invokes the acs.PutDocTag API asynchronously
// api document: https://help.aliyun.com/api/acs/putdoctag.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) PutDocTagWithChan(request *PutDocTagRequest) (<-chan *PutDocTagResponse, <-chan error) {
responseChan := make(chan *PutDocTagResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.PutDocTag(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// PutDocTagWithCallback invokes the acs.PutDocTag API asynchronously
// api document: https://help.aliyun.com/api/acs/putdoctag.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) PutDocTagWithCallback(request *PutDocTagRequest, callback func(response *PutDocTagResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *PutDocTagResponse
var err error
defer close(result)
response, err = client.PutDocTag(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// PutDocTagRequest is the request struct for api PutDocTag
type PutDocTagRequest struct {
*requests.RoaRequest
                    ContentLength     requests.Integer `position:"Header" name:"Content-Length"`
                    Product     string `position:"Path" name:"Product"`
                    BodyContent     string `position:"Body" name:"BodyContent"`
                    TagId     string `position:"Path" name:"TagId"`
                    ContentMD5     string `position:"Header" name:"Content-MD5"`
                    ContentType     string `position:"Header" name:"Content-Type"`
                    Language     string `position:"Path" name:"Language"`
                    Accept     string `position:"Header" name:"Accept"`
}


// PutDocTagResponse is the response struct for api PutDocTag
type PutDocTagResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
}

// CreatePutDocTagRequest creates a request to invoke PutDocTag API
func CreatePutDocTagRequest() (request *PutDocTagRequest) {
request = &PutDocTagRequest{
RoaRequest: &requests.RoaRequest{},
}
request.InitWithApiInfo("Acs", "2015-01-01", "PutDocTag", "/DocTag/[Product]/[TagId]/[Language]", "", "")
request.Method = requests.PUT
return
}

// CreatePutDocTagResponse creates a response to parse from PutDocTag response
func CreatePutDocTagResponse() (response *PutDocTagResponse) {
response = &PutDocTagResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


