
package acs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// PutAccountBinding invokes the acs.PutAccountBinding API synchronously
// api document: https://help.aliyun.com/api/acs/putaccountbinding.html
func (client *Client) PutAccountBinding(request *PutAccountBindingRequest) (response *PutAccountBindingResponse, err error) {
response = CreatePutAccountBindingResponse()
err = client.DoAction(request, response)
return
}

// PutAccountBindingWithChan invokes the acs.PutAccountBinding API asynchronously
// api document: https://help.aliyun.com/api/acs/putaccountbinding.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) PutAccountBindingWithChan(request *PutAccountBindingRequest) (<-chan *PutAccountBindingResponse, <-chan error) {
responseChan := make(chan *PutAccountBindingResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.PutAccountBinding(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// PutAccountBindingWithCallback invokes the acs.PutAccountBinding API asynchronously
// api document: https://help.aliyun.com/api/acs/putaccountbinding.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) PutAccountBindingWithCallback(request *PutAccountBindingRequest, callback func(response *PutAccountBindingResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *PutAccountBindingResponse
var err error
defer close(result)
response, err = client.PutAccountBinding(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// PutAccountBindingRequest is the request struct for api PutAccountBinding
type PutAccountBindingRequest struct {
*requests.RoaRequest
                    Product     string `position:"Path" name:"Product"`
                    AliyunUid     requests.Integer `position:"Path" name:"AliyunUid"`
                    BucEmpId     string `position:"Path" name:"BucEmpId"`
                    Accept     string `position:"Header" name:"Accept"`
}


// PutAccountBindingResponse is the response struct for api PutAccountBinding
type PutAccountBindingResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
}

// CreatePutAccountBindingRequest creates a request to invoke PutAccountBinding API
func CreatePutAccountBindingRequest() (request *PutAccountBindingRequest) {
request = &PutAccountBindingRequest{
RoaRequest: &requests.RoaRequest{},
}
request.InitWithApiInfo("Acs", "2015-01-01", "PutAccountBinding", "/AccountBinding/[Product]/[AliyunUid]/[BucEmpId]", "", "")
request.Method = requests.PUT
return
}

// CreatePutAccountBindingResponse creates a response to parse from PutAccountBinding response
func CreatePutAccountBindingResponse() (response *PutAccountBindingResponse) {
response = &PutAccountBindingResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


