
package acs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// PutVersionParameters invokes the acs.PutVersionParameters API synchronously
// api document: https://help.aliyun.com/api/acs/putversionparameters.html
func (client *Client) PutVersionParameters(request *PutVersionParametersRequest) (response *PutVersionParametersResponse, err error) {
response = CreatePutVersionParametersResponse()
err = client.DoAction(request, response)
return
}

// PutVersionParametersWithChan invokes the acs.PutVersionParameters API asynchronously
// api document: https://help.aliyun.com/api/acs/putversionparameters.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) PutVersionParametersWithChan(request *PutVersionParametersRequest) (<-chan *PutVersionParametersResponse, <-chan error) {
responseChan := make(chan *PutVersionParametersResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.PutVersionParameters(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// PutVersionParametersWithCallback invokes the acs.PutVersionParameters API asynchronously
// api document: https://help.aliyun.com/api/acs/putversionparameters.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) PutVersionParametersWithCallback(request *PutVersionParametersRequest, callback func(response *PutVersionParametersResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *PutVersionParametersResponse
var err error
defer close(result)
response, err = client.PutVersionParameters(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// PutVersionParametersRequest is the request struct for api PutVersionParameters
type PutVersionParametersRequest struct {
*requests.RoaRequest
                    ContentLength     requests.Integer `position:"Header" name:"Content-Length"`
                    BodyContent     string `position:"Body" name:"BodyContent"`
                    ContentMD5     string `position:"Header" name:"Content-MD5"`
                    ProductName     string `position:"Path" name:"ProductName"`
                    ContentType     string `position:"Header" name:"Content-Type"`
                    VersionName     string `position:"Path" name:"VersionName"`
                    Accept     string `position:"Header" name:"Accept"`
}


// PutVersionParametersResponse is the response struct for api PutVersionParameters
type PutVersionParametersResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
}

// CreatePutVersionParametersRequest creates a request to invoke PutVersionParameters API
func CreatePutVersionParametersRequest() (request *PutVersionParametersRequest) {
request = &PutVersionParametersRequest{
RoaRequest: &requests.RoaRequest{},
}
request.InitWithApiInfo("Acs", "2015-01-01", "PutVersionParameters", "/Parameters/[ProductName]/[VersionName]", "", "")
request.Method = requests.PUT
return
}

// CreatePutVersionParametersResponse creates a response to parse from PutVersionParameters response
func CreatePutVersionParametersResponse() (response *PutVersionParametersResponse) {
response = &PutVersionParametersResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


