
package ams

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// QueryAppInfo invokes the ams.QueryAppInfo API synchronously
// api document: https://help.aliyun.com/api/ams/queryappinfo.html
func (client *Client) QueryAppInfo(request *QueryAppInfoRequest) (response *QueryAppInfoResponse, err error) {
response = CreateQueryAppInfoResponse()
err = client.DoAction(request, response)
return
}

// QueryAppInfoWithChan invokes the ams.QueryAppInfo API asynchronously
// api document: https://help.aliyun.com/api/ams/queryappinfo.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) QueryAppInfoWithChan(request *QueryAppInfoRequest) (<-chan *QueryAppInfoResponse, <-chan error) {
responseChan := make(chan *QueryAppInfoResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.QueryAppInfo(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// QueryAppInfoWithCallback invokes the ams.QueryAppInfo API asynchronously
// api document: https://help.aliyun.com/api/ams/queryappinfo.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) QueryAppInfoWithCallback(request *QueryAppInfoRequest, callback func(response *QueryAppInfoResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *QueryAppInfoResponse
var err error
defer close(result)
response, err = client.QueryAppInfo(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// QueryAppInfoRequest is the request struct for api QueryAppInfo
type QueryAppInfoRequest struct {
*requests.RpcRequest
                    OwnerId     requests.Integer `position:"Query" name:"OwnerId"`
                    AppKey     requests.Integer `position:"Query" name:"AppKey"`
}


// QueryAppInfoResponse is the response struct for api QueryAppInfo
type QueryAppInfoResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
            Code     string `json:"Code" xml:"Code"`
            AppInfo AppInfo  `json:"AppInfo" xml:"AppInfo"`
}

// CreateQueryAppInfoRequest creates a request to invoke QueryAppInfo API
func CreateQueryAppInfoRequest() (request *QueryAppInfoRequest) {
request = &QueryAppInfoRequest{
RpcRequest: &requests.RpcRequest{},
}
request.InitWithApiInfo("AMS", "2018-02-12", "QueryAppInfo", "", "")
return
}

// CreateQueryAppInfoResponse creates a response to parse from QueryAppInfo response
func CreateQueryAppInfoResponse() (response *QueryAppInfoResponse) {
response = &QueryAppInfoResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


