
package yundun

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// SetDdosAuto invokes the yundun.SetDdosAuto API synchronously
// api document: https://help.aliyun.com/api/yundun/setddosauto.html
func (client *Client) SetDdosAuto(request *SetDdosAutoRequest) (response *SetDdosAutoResponse, err error) {
response = CreateSetDdosAutoResponse()
err = client.DoAction(request, response)
return
}

// SetDdosAutoWithChan invokes the yundun.SetDdosAuto API asynchronously
// api document: https://help.aliyun.com/api/yundun/setddosauto.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) SetDdosAutoWithChan(request *SetDdosAutoRequest) (<-chan *SetDdosAutoResponse, <-chan error) {
responseChan := make(chan *SetDdosAutoResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.SetDdosAuto(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// SetDdosAutoWithCallback invokes the yundun.SetDdosAuto API asynchronously
// api document: https://help.aliyun.com/api/yundun/setddosauto.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) SetDdosAutoWithCallback(request *SetDdosAutoRequest, callback func(response *SetDdosAutoResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *SetDdosAutoResponse
var err error
defer close(result)
response, err = client.SetDdosAuto(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// SetDdosAutoRequest is the request struct for api SetDdosAuto
type SetDdosAutoRequest struct {
*requests.RpcRequest
                    InstanceId     string `position:"Query" name:"InstanceId"`
                    InstanceType     string `position:"Query" name:"InstanceType"`
}


// SetDdosAutoResponse is the response struct for api SetDdosAuto
type SetDdosAutoResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
}

// CreateSetDdosAutoRequest creates a request to invoke SetDdosAuto API
func CreateSetDdosAutoRequest() (request *SetDdosAutoRequest) {
request = &SetDdosAutoRequest{
RpcRequest: &requests.RpcRequest{},
}
request.InitWithApiInfo("Yundun", "2015-04-16", "SetDdosAuto", "yundun", "openAPI")
return
}

// CreateSetDdosAutoResponse creates a response to parse from SetDdosAuto response
func CreateSetDdosAutoResponse() (response *SetDdosAutoResponse) {
response = &SetDdosAutoResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


