
package yundun

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

// InstanceInfo is a nested struct in yundun response
type InstanceInfo struct {
            Region     string `json:"Region" xml:"Region"`
            RegionName     string `json:"RegionName" xml:"RegionName"`
            RegionEnName     string `json:"RegionEnName" xml:"RegionEnName"`
            InstanceName     string `json:"InstanceName" xml:"InstanceName"`
            InstanceId     string `json:"InstanceId" xml:"InstanceId"`
            Ip     string `json:"Ip" xml:"Ip"`
            InternetIp     string `json:"InternetIp" xml:"InternetIp"`
            IntranetIp     string `json:"IntranetIp" xml:"IntranetIp"`
            Ddos     int `json:"Ddos" xml:"Ddos"`
            HostEvent     int `json:"HostEvent" xml:"HostEvent"`
            SecureCheck     int `json:"SecureCheck" xml:"SecureCheck"`
            AegisStatus     int `json:"AegisStatus" xml:"AegisStatus"`
            Waf     int `json:"Waf" xml:"Waf"`
            IsLock     bool `json:"IsLock" xml:"IsLock"`
            LockType     string `json:"LockType" xml:"LockType"`
            UnLockTimes     int `json:"UnLockTimes" xml:"UnLockTimes"`
            TriggerTime     string `json:"TriggerTime" xml:"TriggerTime"`
}
