
package yundun

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// TodayBackdoor invokes the yundun.TodayBackdoor API synchronously
// api document: https://help.aliyun.com/api/yundun/todaybackdoor.html
func (client *Client) TodayBackdoor(request *TodayBackdoorRequest) (response *TodayBackdoorResponse, err error) {
response = CreateTodayBackdoorResponse()
err = client.DoAction(request, response)
return
}

// TodayBackdoorWithChan invokes the yundun.TodayBackdoor API asynchronously
// api document: https://help.aliyun.com/api/yundun/todaybackdoor.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) TodayBackdoorWithChan(request *TodayBackdoorRequest) (<-chan *TodayBackdoorResponse, <-chan error) {
responseChan := make(chan *TodayBackdoorResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.TodayBackdoor(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// TodayBackdoorWithCallback invokes the yundun.TodayBackdoor API asynchronously
// api document: https://help.aliyun.com/api/yundun/todaybackdoor.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) TodayBackdoorWithCallback(request *TodayBackdoorRequest, callback func(response *TodayBackdoorResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *TodayBackdoorResponse
var err error
defer close(result)
response, err = client.TodayBackdoor(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// TodayBackdoorRequest is the request struct for api TodayBackdoor
type TodayBackdoorRequest struct {
*requests.RpcRequest
}


// TodayBackdoorResponse is the response struct for api TodayBackdoor
type TodayBackdoorResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
            Backdoor     int64 `json:"Backdoor" xml:"Backdoor"`
}

// CreateTodayBackdoorRequest creates a request to invoke TodayBackdoor API
func CreateTodayBackdoorRequest() (request *TodayBackdoorRequest) {
request = &TodayBackdoorRequest{
RpcRequest: &requests.RpcRequest{},
}
request.InitWithApiInfo("Yundun", "2015-02-27", "TodayBackdoor", "yundun", "openAPI")
return
}

// CreateTodayBackdoorResponse creates a response to parse from TodayBackdoor response
func CreateTodayBackdoorResponse() (response *TodayBackdoorResponse) {
response = &TodayBackdoorResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


