
package yundun

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// WafLog invokes the yundun.WafLog API synchronously
// api document: https://help.aliyun.com/api/yundun/waflog.html
func (client *Client) WafLog(request *WafLogRequest) (response *WafLogResponse, err error) {
response = CreateWafLogResponse()
err = client.DoAction(request, response)
return
}

// WafLogWithChan invokes the yundun.WafLog API asynchronously
// api document: https://help.aliyun.com/api/yundun/waflog.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) WafLogWithChan(request *WafLogRequest) (<-chan *WafLogResponse, <-chan error) {
responseChan := make(chan *WafLogResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.WafLog(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// WafLogWithCallback invokes the yundun.WafLog API asynchronously
// api document: https://help.aliyun.com/api/yundun/waflog.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) WafLogWithCallback(request *WafLogRequest, callback func(response *WafLogResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *WafLogResponse
var err error
defer close(result)
response, err = client.WafLog(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// WafLogRequest is the request struct for api WafLog
type WafLogRequest struct {
*requests.RpcRequest
                    JstOwnerId     requests.Integer `position:"Query" name:"JstOwnerId"`
                    InstanceId     string `position:"Query" name:"InstanceId"`
                    PageSize     requests.Integer `position:"Query" name:"PageSize"`
                    InstanceType     string `position:"Query" name:"InstanceType"`
                    PageNumber     requests.Integer `position:"Query" name:"PageNumber"`
}


// WafLogResponse is the response struct for api WafLog
type WafLogResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
            WebAttack     int `json:"WebAttack" xml:"WebAttack"`
            NewWafUser     bool `json:"NewWafUser" xml:"NewWafUser"`
            WafOpened     bool `json:"WafOpened" xml:"WafOpened"`
            InWhiteList     bool `json:"InWhiteList" xml:"InWhiteList"`
            DomainCount     int `json:"DomainCount" xml:"DomainCount"`
            StartTime     string `json:"StartTime" xml:"StartTime"`
            EndTime     string `json:"EndTime" xml:"EndTime"`
            PageNumber     int `json:"PageNumber" xml:"PageNumber"`
            PageSize     int `json:"PageSize" xml:"PageSize"`
            TotalCount     int `json:"TotalCount" xml:"TotalCount"`
                    LogList LogListInWafLog `json:"LogList" xml:"LogList"`
}

// CreateWafLogRequest creates a request to invoke WafLog API
func CreateWafLogRequest() (request *WafLogRequest) {
request = &WafLogRequest{
RpcRequest: &requests.RpcRequest{},
}
request.InitWithApiInfo("Yundun", "2015-04-16", "WafLog", "yundun", "openAPI")
return
}

// CreateWafLogResponse creates a response to parse from WafLog response
func CreateWafLogResponse() (response *WafLogResponse) {
response = &WafLogResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


