package ecsdemo

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

// ResourceType is a nested struct in ecsdemo response
type ResourceType struct {
	Product                       string                        `json:"Product" xml:"Product"`
	ResourceTypeCode              string                        `json:"ResourceTypeCode" xml:"ResourceTypeCode"`
	ResourceTypeVersion           string                        `json:"ResourceTypeVersion" xml:"ResourceTypeVersion"`
	Title                         string                        `json:"Title" xml:"Title"`
	UniqueIdentifier              string                        `json:"UniqueIdentifier" xml:"UniqueIdentifier"`
	Description                   string                        `json:"Description" xml:"Description"`
	DeliveryScope                 string                        `json:"DeliveryScope" xml:"DeliveryScope"`
	ResourceIdField               bool                          `json:"ResourceIdField" xml:"ResourceIdField"`
	Definitions                   map[string]interface{}        `json:"Definitions" xml:"Definitions"`
	SchemaRef                     string                        `json:"SchemaRef" xml:"SchemaRef"`
	OperationAPI                  OperationAPI                  `json:"OperationAPI" xml:"OperationAPI"`
	ResourceTypeAttributeMappings ResourceTypeAttributeMappings `json:"ResourceTypeAttributeMappings" xml:"ResourceTypeAttributeMappings"`
	CommonAttributeMark           CommonAttributeMark           `json:"CommonAttributeMark" xml:"CommonAttributeMark"`
	States                        []State                       `json:"States" xml:"States"`
}
