
package rds

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// CreateOrderForRebuild invokes the rds.CreateOrderForRebuild API synchronously
// api document: https://help.aliyun.com/api/rds/createorderforrebuild.html
func (client *Client) CreateOrderForRebuild(request *CreateOrderForRebuildRequest) (response *CreateOrderForRebuildResponse, err error) {
response = CreateCreateOrderForRebuildResponse()
err = client.DoAction(request, response)
return
}

// CreateOrderForRebuildWithChan invokes the rds.CreateOrderForRebuild API asynchronously
// api document: https://help.aliyun.com/api/rds/createorderforrebuild.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) CreateOrderForRebuildWithChan(request *CreateOrderForRebuildRequest) (<-chan *CreateOrderForRebuildResponse, <-chan error) {
responseChan := make(chan *CreateOrderForRebuildResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.CreateOrderForRebuild(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// CreateOrderForRebuildWithCallback invokes the rds.CreateOrderForRebuild API asynchronously
// api document: https://help.aliyun.com/api/rds/createorderforrebuild.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) CreateOrderForRebuildWithCallback(request *CreateOrderForRebuildRequest, callback func(response *CreateOrderForRebuildResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *CreateOrderForRebuildResponse
var err error
defer close(result)
response, err = client.CreateOrderForRebuild(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// CreateOrderForRebuildRequest is the request struct for api CreateOrderForRebuild
type CreateOrderForRebuildRequest struct {
*requests.RpcRequest
                    ResourceOwnerId     requests.Integer `position:"Query" name:"ResourceOwnerId"`
                    ClientToken     string `position:"Query" name:"ClientToken"`
                    ResourceGroupId     string `position:"Query" name:"ResourceGroupId"`
                    DBInstanceId     string `position:"Query" name:"DBInstanceId"`
                    DBInstanceDescription     string `position:"Query" name:"DBInstanceDescription"`
                    BusinessInfo     string `position:"Query" name:"BusinessInfo"`
                    AgentId     string `position:"Query" name:"AgentId"`
                    AutoPay     requests.Boolean `position:"Query" name:"AutoPay"`
                    ResourceOwnerAccount     string `position:"Query" name:"ResourceOwnerAccount"`
                    Resource     string `position:"Query" name:"Resource"`
                    OwnerAccount     string `position:"Query" name:"OwnerAccount"`
                    CommodityCode     string `position:"Query" name:"CommodityCode"`
                    OwnerId     requests.Integer `position:"Query" name:"OwnerId"`
                    UsedTime     string `position:"Query" name:"UsedTime"`
                    DBInstanceClass     string `position:"Query" name:"DBInstanceClass"`
                    VSwitchId     string `position:"Query" name:"VSwitchId"`
                    RebuildInstanceFlag     requests.Boolean `position:"Query" name:"RebuildInstanceFlag"`
                    AutoRenew     string `position:"Query" name:"AutoRenew"`
                    PromotionCode     string `position:"Query" name:"PromotionCode"`
                    VPCId     string `position:"Query" name:"VPCId"`
                    ZoneId     string `position:"Query" name:"ZoneId"`
                    TimeType     string `position:"Query" name:"TimeType"`
                    PayType     string `position:"Query" name:"PayType"`
                    InstanceNetworkType     string `position:"Query" name:"InstanceNetworkType"`
}


// CreateOrderForRebuildResponse is the response struct for api CreateOrderForRebuild
type CreateOrderForRebuildResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
            DBInstanceId     string `json:"DBInstanceId" xml:"DBInstanceId"`
            OrderId     int `json:"OrderId" xml:"OrderId"`
}

// CreateCreateOrderForRebuildRequest creates a request to invoke CreateOrderForRebuild API
func CreateCreateOrderForRebuildRequest() (request *CreateOrderForRebuildRequest) {
request = &CreateOrderForRebuildRequest{
RpcRequest: &requests.RpcRequest{},
}
request.InitWithApiInfo("Rds", "2014-08-15", "CreateOrderForRebuild", "rds", "openAPI")
return
}

// CreateCreateOrderForRebuildResponse creates a response to parse from CreateOrderForRebuild response
func CreateCreateOrderForRebuildResponse() (response *CreateOrderForRebuildResponse) {
response = &CreateOrderForRebuildResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


