
package rds

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// DescribeRegionsForChannel invokes the rds.DescribeRegionsForChannel API synchronously
// api document: https://help.aliyun.com/api/rds/describeregionsforchannel.html
func (client *Client) DescribeRegionsForChannel(request *DescribeRegionsForChannelRequest) (response *DescribeRegionsForChannelResponse, err error) {
response = CreateDescribeRegionsForChannelResponse()
err = client.DoAction(request, response)
return
}

// DescribeRegionsForChannelWithChan invokes the rds.DescribeRegionsForChannel API asynchronously
// api document: https://help.aliyun.com/api/rds/describeregionsforchannel.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) DescribeRegionsForChannelWithChan(request *DescribeRegionsForChannelRequest) (<-chan *DescribeRegionsForChannelResponse, <-chan error) {
responseChan := make(chan *DescribeRegionsForChannelResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.DescribeRegionsForChannel(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// DescribeRegionsForChannelWithCallback invokes the rds.DescribeRegionsForChannel API asynchronously
// api document: https://help.aliyun.com/api/rds/describeregionsforchannel.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) DescribeRegionsForChannelWithCallback(request *DescribeRegionsForChannelRequest, callback func(response *DescribeRegionsForChannelResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *DescribeRegionsForChannelResponse
var err error
defer close(result)
response, err = client.DescribeRegionsForChannel(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// DescribeRegionsForChannelRequest is the request struct for api DescribeRegionsForChannel
type DescribeRegionsForChannelRequest struct {
*requests.RpcRequest
                    ResourceOwnerId     requests.Integer `position:"Query" name:"ResourceOwnerId"`
                    ResourceOwnerAccount     string `position:"Query" name:"ResourceOwnerAccount"`
                    ClientToken     string `position:"Query" name:"ClientToken"`
                    OwnerAccount     string `position:"Query" name:"OwnerAccount"`
                    OwnerId     requests.Integer `position:"Query" name:"OwnerId"`
}


// DescribeRegionsForChannelResponse is the response struct for api DescribeRegionsForChannel
type DescribeRegionsForChannelResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
                    Regions RegionsInDescribeRegionsForChannel `json:"Regions" xml:"Regions"`
}

// CreateDescribeRegionsForChannelRequest creates a request to invoke DescribeRegionsForChannel API
func CreateDescribeRegionsForChannelRequest() (request *DescribeRegionsForChannelRequest) {
request = &DescribeRegionsForChannelRequest{
RpcRequest: &requests.RpcRequest{},
}
request.InitWithApiInfo("Rds", "2014-08-15", "DescribeRegionsForChannel", "rds", "openAPI")
return
}

// CreateDescribeRegionsForChannelResponse creates a response to parse from DescribeRegionsForChannel response
func CreateDescribeRegionsForChannelResponse() (response *DescribeRegionsForChannelResponse) {
response = &DescribeRegionsForChannelResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


