
package rds

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// DescribeDBInstancesWithCloudResource invokes the rds.DescribeDBInstancesWithCloudResource API synchronously
// api document: https://help.aliyun.com/api/rds/describedbinstanceswithcloudresource.html
func (client *Client) DescribeDBInstancesWithCloudResource(request *DescribeDBInstancesWithCloudResourceRequest) (response *DescribeDBInstancesWithCloudResourceResponse, err error) {
response = CreateDescribeDBInstancesWithCloudResourceResponse()
err = client.DoAction(request, response)
return
}

// DescribeDBInstancesWithCloudResourceWithChan invokes the rds.DescribeDBInstancesWithCloudResource API asynchronously
// api document: https://help.aliyun.com/api/rds/describedbinstanceswithcloudresource.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) DescribeDBInstancesWithCloudResourceWithChan(request *DescribeDBInstancesWithCloudResourceRequest) (<-chan *DescribeDBInstancesWithCloudResourceResponse, <-chan error) {
responseChan := make(chan *DescribeDBInstancesWithCloudResourceResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.DescribeDBInstancesWithCloudResource(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// DescribeDBInstancesWithCloudResourceWithCallback invokes the rds.DescribeDBInstancesWithCloudResource API asynchronously
// api document: https://help.aliyun.com/api/rds/describedbinstanceswithcloudresource.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) DescribeDBInstancesWithCloudResourceWithCallback(request *DescribeDBInstancesWithCloudResourceRequest, callback func(response *DescribeDBInstancesWithCloudResourceResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *DescribeDBInstancesWithCloudResourceResponse
var err error
defer close(result)
response, err = client.DescribeDBInstancesWithCloudResource(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// DescribeDBInstancesWithCloudResourceRequest is the request struct for api DescribeDBInstancesWithCloudResource
type DescribeDBInstancesWithCloudResourceRequest struct {
*requests.RpcRequest
                    ResourceOwnerId     requests.Integer `position:"Query" name:"ResourceOwnerId"`
                    PageNumber     requests.Integer `position:"Query" name:"PageNumber"`
                    SecurityToken     string `position:"Query" name:"SecurityToken"`
                    PageSize     requests.Integer `position:"Query" name:"PageSize"`
                    ResourceOwnerAccount     string `position:"Query" name:"ResourceOwnerAccount"`
                    OwnerAccount     string `position:"Query" name:"OwnerAccount"`
                    EncryptionKey     string `position:"Query" name:"EncryptionKey"`
                    OwnerId     requests.Integer `position:"Query" name:"OwnerId"`
                    RoleArn     string `position:"Query" name:"RoleArn"`
}


// DescribeDBInstancesWithCloudResourceResponse is the response struct for api DescribeDBInstancesWithCloudResource
type DescribeDBInstancesWithCloudResourceResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
                    DBInstanceNameList DBInstanceNameList `json:"DBInstanceNameList" xml:"DBInstanceNameList"`
}

// CreateDescribeDBInstancesWithCloudResourceRequest creates a request to invoke DescribeDBInstancesWithCloudResource API
func CreateDescribeDBInstancesWithCloudResourceRequest() (request *DescribeDBInstancesWithCloudResourceRequest) {
request = &DescribeDBInstancesWithCloudResourceRequest{
RpcRequest: &requests.RpcRequest{},
}
request.InitWithApiInfo("Rds", "2014-08-15", "DescribeDBInstancesWithCloudResource", "rds", "openAPI")
return
}

// CreateDescribeDBInstancesWithCloudResourceResponse creates a response to parse from DescribeDBInstancesWithCloudResource response
func CreateDescribeDBInstancesWithCloudResourceResponse() (response *DescribeDBInstancesWithCloudResourceResponse) {
response = &DescribeDBInstancesWithCloudResourceResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


