
package rds

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// ResetAdminAccountPassword invokes the rds.ResetAdminAccountPassword API synchronously
// api document: https://help.aliyun.com/api/rds/resetadminaccountpassword.html
func (client *Client) ResetAdminAccountPassword(request *ResetAdminAccountPasswordRequest) (response *ResetAdminAccountPasswordResponse, err error) {
response = CreateResetAdminAccountPasswordResponse()
err = client.DoAction(request, response)
return
}

// ResetAdminAccountPasswordWithChan invokes the rds.ResetAdminAccountPassword API asynchronously
// api document: https://help.aliyun.com/api/rds/resetadminaccountpassword.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) ResetAdminAccountPasswordWithChan(request *ResetAdminAccountPasswordRequest) (<-chan *ResetAdminAccountPasswordResponse, <-chan error) {
responseChan := make(chan *ResetAdminAccountPasswordResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.ResetAdminAccountPassword(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// ResetAdminAccountPasswordWithCallback invokes the rds.ResetAdminAccountPassword API asynchronously
// api document: https://help.aliyun.com/api/rds/resetadminaccountpassword.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) ResetAdminAccountPasswordWithCallback(request *ResetAdminAccountPasswordRequest, callback func(response *ResetAdminAccountPasswordResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *ResetAdminAccountPasswordResponse
var err error
defer close(result)
response, err = client.ResetAdminAccountPassword(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// ResetAdminAccountPasswordRequest is the request struct for api ResetAdminAccountPassword
type ResetAdminAccountPasswordRequest struct {
*requests.RpcRequest
                    ResourceOwnerId     requests.Integer `position:"Query" name:"ResourceOwnerId"`
                    AccountName     string `position:"Query" name:"AccountName"`
                    DBInstanceId     string `position:"Query" name:"DBInstanceId"`
                    ResourceOwnerAccount     string `position:"Query" name:"ResourceOwnerAccount"`
                    OwnerAccount     string `position:"Query" name:"OwnerAccount"`
                    OwnerId     requests.Integer `position:"Query" name:"OwnerId"`
                    AccountPassword     string `position:"Query" name:"AccountPassword"`
}


// ResetAdminAccountPasswordResponse is the response struct for api ResetAdminAccountPassword
type ResetAdminAccountPasswordResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
}

// CreateResetAdminAccountPasswordRequest creates a request to invoke ResetAdminAccountPassword API
func CreateResetAdminAccountPasswordRequest() (request *ResetAdminAccountPasswordRequest) {
request = &ResetAdminAccountPasswordRequest{
RpcRequest: &requests.RpcRequest{},
}
request.InitWithApiInfo("Rds", "2014-08-15", "ResetAdminAccountPassword", "rds", "openAPI")
return
}

// CreateResetAdminAccountPasswordResponse creates a response to parse from ResetAdminAccountPassword response
func CreateResetAdminAccountPasswordResponse() (response *ResetAdminAccountPasswordResponse) {
response = &ResetAdminAccountPasswordResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


