
package rds

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

// SQLLog is a nested struct in rds response
type SQLLog struct {
            SQLServerTotalExecutionCounts     int `json:"SQLServerTotalExecutionCounts" xml:"SQLServerTotalExecutionCounts"`
            SQLServerTotalExecutionTimes     int `json:"SQLServerTotalExecutionTimes" xml:"SQLServerTotalExecutionTimes"`
            HostAddress     string `json:"HostAddress" xml:"HostAddress"`
            TotalLockTimes     int `json:"TotalLockTimes" xml:"TotalLockTimes"`
            TotalPhysicalReadCounts     int `json:"TotalPhysicalReadCounts" xml:"TotalPhysicalReadCounts"`
            MaxlockTime     int `json:"MaxlockTime" xml:"MaxlockTime"`
            MySQLTotalExecutionCounts     int `json:"MySQLTotalExecutionCounts" xml:"MySQLTotalExecutionCounts"`
            CreateTime     string `json:"CreateTime" xml:"CreateTime"`
            ParseRowCounts     int `json:"ParseRowCounts" xml:"ParseRowCounts"`
            ReportTime     string `json:"ReportTime" xml:"ReportTime"`
            ReturnTotalRowCounts     int `json:"ReturnTotalRowCounts" xml:"ReturnTotalRowCounts"`
            SQLText     string `json:"SQLText" xml:"SQLText"`
            ExecutionStartTime     string `json:"ExecutionStartTime" xml:"ExecutionStartTime"`
            ReturnMaxRowCount     int `json:"ReturnMaxRowCount" xml:"ReturnMaxRowCount"`
            ReturnRowCounts     int `json:"ReturnRowCounts" xml:"ReturnRowCounts"`
            MaxExecutionTime     int `json:"MaxExecutionTime" xml:"MaxExecutionTime"`
            QueryTimes     int `json:"QueryTimes" xml:"QueryTimes"`
            DBName     string `json:"DBName" xml:"DBName"`
            TotalLogicalReadCounts     int `json:"TotalLogicalReadCounts" xml:"TotalLogicalReadCounts"`
            MySQLTotalExecutionTimes     int `json:"MySQLTotalExecutionTimes" xml:"MySQLTotalExecutionTimes"`
            LockTimes     int `json:"LockTimes" xml:"LockTimes"`
            ParseTotalRowCounts     int `json:"ParseTotalRowCounts" xml:"ParseTotalRowCounts"`
            ParseMaxRowCount     int `json:"ParseMaxRowCount" xml:"ParseMaxRowCount"`
}
