package ecs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// ArchiveInstance invokes the ecs.ArchiveInstance API synchronously
func (client *Client) ArchiveInstance(request *ArchiveInstanceRequest) (response *ArchiveInstanceResponse, err error) {
	response = CreateArchiveInstanceResponse()
	err = client.DoAction(request, response)
	return
}

// ArchiveInstanceWithChan invokes the ecs.ArchiveInstance API asynchronously
func (client *Client) ArchiveInstanceWithChan(request *ArchiveInstanceRequest) (<-chan *ArchiveInstanceResponse, <-chan error) {
	responseChan := make(chan *ArchiveInstanceResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.ArchiveInstance(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// ArchiveInstanceWithCallback invokes the ecs.ArchiveInstance API asynchronously
func (client *Client) ArchiveInstanceWithCallback(request *ArchiveInstanceRequest, callback func(response *ArchiveInstanceResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *ArchiveInstanceResponse
		var err error
		defer close(result)
		response, err = client.ArchiveInstance(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// ArchiveInstanceRequest is the request struct for api ArchiveInstance
type ArchiveInstanceRequest struct {
	*requests.RpcRequest
	ResourceOwnerId      requests.Integer `position:"Query" name:"ResourceOwnerId"`
	ResourceOwnerAccount string           `position:"Query" name:"ResourceOwnerAccount"`
	OwnerAccount         string           `position:"Query" name:"OwnerAccount"`
	OwnerId              requests.Integer `position:"Query" name:"OwnerId"`
	InstanceId           string           `position:"Query" name:"InstanceId"`
}

// ArchiveInstanceResponse is the response struct for api ArchiveInstance
type ArchiveInstanceResponse struct {
	*responses.BaseResponse
	RequestId string `json:"RequestId" xml:"RequestId"`
}

// CreateArchiveInstanceRequest creates a request to invoke ArchiveInstance API
func CreateArchiveInstanceRequest() (request *ArchiveInstanceRequest) {
	request = &ArchiveInstanceRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("Ecs", "2014-05-26", "ArchiveInstance", "ecs", "openAPI")
	request.Method = requests.POST
	return
}

// CreateArchiveInstanceResponse creates a response to parse from ArchiveInstance response
func CreateArchiveInstanceResponse() (response *ArchiveInstanceResponse) {
	response = &ArchiveInstanceResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
