
package ecs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// AuthorizeSecurityGroupEgress_GatedLaunch invokes the ecs.AuthorizeSecurityGroupEgress_GatedLaunch API synchronously
// api document: https://help.aliyun.com/api/ecs/authorizesecuritygroupegress_gatedlaunch.html
func (client *Client) AuthorizeSecurityGroupEgress_GatedLaunch(request *AuthorizeSecurityGroupEgress_GatedLaunchRequest) (response *AuthorizeSecurityGroupEgress_GatedLaunchResponse, err error) {
response = CreateAuthorizeSecurityGroupEgress_GatedLaunchResponse()
err = client.DoAction(request, response)
return
}

// AuthorizeSecurityGroupEgress_GatedLaunchWithChan invokes the ecs.AuthorizeSecurityGroupEgress_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/authorizesecuritygroupegress_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) AuthorizeSecurityGroupEgress_GatedLaunchWithChan(request *AuthorizeSecurityGroupEgress_GatedLaunchRequest) (<-chan *AuthorizeSecurityGroupEgress_GatedLaunchResponse, <-chan error) {
responseChan := make(chan *AuthorizeSecurityGroupEgress_GatedLaunchResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.AuthorizeSecurityGroupEgress_GatedLaunch(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// AuthorizeSecurityGroupEgress_GatedLaunchWithCallback invokes the ecs.AuthorizeSecurityGroupEgress_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/authorizesecuritygroupegress_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) AuthorizeSecurityGroupEgress_GatedLaunchWithCallback(request *AuthorizeSecurityGroupEgress_GatedLaunchRequest, callback func(response *AuthorizeSecurityGroupEgress_GatedLaunchResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *AuthorizeSecurityGroupEgress_GatedLaunchResponse
var err error
defer close(result)
response, err = client.AuthorizeSecurityGroupEgress_GatedLaunch(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// AuthorizeSecurityGroupEgress_GatedLaunchRequest is the request struct for api AuthorizeSecurityGroupEgress_GatedLaunch
type AuthorizeSecurityGroupEgress_GatedLaunchRequest struct {
*requests.RpcRequest
                    NicType     string `position:"Query" name:"NicType"`
                    ResourceOwnerId     requests.Integer `position:"Query" name:"ResourceOwnerId"`
                    ClientToken     string `position:"Query" name:"ClientToken"`
                    SecurityGroupId     string `position:"Query" name:"SecurityGroupId"`
                    Policy     string `position:"Query" name:"Policy"`
                    PortRange     string `position:"Query" name:"PortRange"`
                    ResourceOwnerAccount     string `position:"Query" name:"ResourceOwnerAccount"`
                    IpProtocol     string `position:"Query" name:"IpProtocol"`
                    OwnerAccount     string `position:"Query" name:"OwnerAccount"`
                    DestGroupId     string `position:"Query" name:"DestGroupId"`
                    OwnerId     requests.Integer `position:"Query" name:"OwnerId"`
                    DestGroupOwnerAccount     string `position:"Query" name:"DestGroupOwnerAccount"`
                    Priority     string `position:"Query" name:"Priority"`
                    DestCidrIp     string `position:"Query" name:"DestCidrIp"`
                    DestGroupOwnerId     requests.Integer `position:"Query" name:"DestGroupOwnerId"`
}


// AuthorizeSecurityGroupEgress_GatedLaunchResponse is the response struct for api AuthorizeSecurityGroupEgress_GatedLaunch
type AuthorizeSecurityGroupEgress_GatedLaunchResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
}

// CreateAuthorizeSecurityGroupEgress_GatedLaunchRequest creates a request to invoke AuthorizeSecurityGroupEgress_GatedLaunch API
func CreateAuthorizeSecurityGroupEgress_GatedLaunchRequest() (request *AuthorizeSecurityGroupEgress_GatedLaunchRequest) {
request = &AuthorizeSecurityGroupEgress_GatedLaunchRequest{
RpcRequest: &requests.RpcRequest{},
}
request.InitWithApiInfo("Ecs", "2014-05-26", "AuthorizeSecurityGroupEgress_GatedLaunch", "", "")
return
}

// CreateAuthorizeSecurityGroupEgress_GatedLaunchResponse creates a response to parse from AuthorizeSecurityGroupEgress_GatedLaunch response
func CreateAuthorizeSecurityGroupEgress_GatedLaunchResponse() (response *AuthorizeSecurityGroupEgress_GatedLaunchResponse) {
response = &AuthorizeSecurityGroupEgress_GatedLaunchResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


