package ecs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// CreateMaintenanceWindow invokes the ecs.CreateMaintenanceWindow API synchronously
func (client *Client) CreateMaintenanceWindow(request *CreateMaintenanceWindowRequest) (response *CreateMaintenanceWindowResponse, err error) {
	response = CreateCreateMaintenanceWindowResponse()
	err = client.DoAction(request, response)
	return
}

// CreateMaintenanceWindowWithChan invokes the ecs.CreateMaintenanceWindow API asynchronously
func (client *Client) CreateMaintenanceWindowWithChan(request *CreateMaintenanceWindowRequest) (<-chan *CreateMaintenanceWindowResponse, <-chan error) {
	responseChan := make(chan *CreateMaintenanceWindowResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.CreateMaintenanceWindow(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// CreateMaintenanceWindowWithCallback invokes the ecs.CreateMaintenanceWindow API asynchronously
func (client *Client) CreateMaintenanceWindowWithCallback(request *CreateMaintenanceWindowRequest, callback func(response *CreateMaintenanceWindowResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *CreateMaintenanceWindowResponse
		var err error
		defer close(result)
		response, err = client.CreateMaintenanceWindow(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// CreateMaintenanceWindowRequest is the request struct for api CreateMaintenanceWindow
type CreateMaintenanceWindowRequest struct {
	*requests.RpcRequest
	ResourceOwnerId      requests.Integer `position:"Query" name:"ResourceOwnerId"`
	StartTime            string           `position:"Query" name:"StartTime"`
	ResourceOwnerAccount string           `position:"Query" name:"ResourceOwnerAccount"`
	Level                string           `position:"Query" name:"Level"`
	OwnerAccount         string           `position:"Query" name:"OwnerAccount"`
	EndTime              string           `position:"Query" name:"EndTime"`
	OwnerId              requests.Integer `position:"Query" name:"OwnerId"`
	InstanceId           string           `position:"Query" name:"InstanceId"`
}

// CreateMaintenanceWindowResponse is the response struct for api CreateMaintenanceWindow
type CreateMaintenanceWindowResponse struct {
	*responses.BaseResponse
	RequestId         string            `json:"RequestId" xml:"RequestId"`
	MaintenanceWindow MaintenanceWindow `json:"MaintenanceWindow" xml:"MaintenanceWindow"`
}

// CreateCreateMaintenanceWindowRequest creates a request to invoke CreateMaintenanceWindow API
func CreateCreateMaintenanceWindowRequest() (request *CreateMaintenanceWindowRequest) {
	request = &CreateMaintenanceWindowRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("Ecs", "2014-05-26", "CreateMaintenanceWindow", "ecs", "openAPI")
	request.Method = requests.POST
	return
}

// CreateCreateMaintenanceWindowResponse creates a response to parse from CreateMaintenanceWindow response
func CreateCreateMaintenanceWindowResponse() (response *CreateMaintenanceWindowResponse) {
	response = &CreateMaintenanceWindowResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
