
package ecs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// CreateEniQosGroup invokes the ecs.CreateEniQosGroup API synchronously
// api document: https://help.aliyun.com/api/ecs/createeniqosgroup.html
func (client *Client) CreateEniQosGroup(request *CreateEniQosGroupRequest) (response *CreateEniQosGroupResponse, err error) {
response = CreateCreateEniQosGroupResponse()
err = client.DoAction(request, response)
return
}

// CreateEniQosGroupWithChan invokes the ecs.CreateEniQosGroup API asynchronously
// api document: https://help.aliyun.com/api/ecs/createeniqosgroup.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) CreateEniQosGroupWithChan(request *CreateEniQosGroupRequest) (<-chan *CreateEniQosGroupResponse, <-chan error) {
responseChan := make(chan *CreateEniQosGroupResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.CreateEniQosGroup(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// CreateEniQosGroupWithCallback invokes the ecs.CreateEniQosGroup API asynchronously
// api document: https://help.aliyun.com/api/ecs/createeniqosgroup.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) CreateEniQosGroupWithCallback(request *CreateEniQosGroupRequest, callback func(response *CreateEniQosGroupResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *CreateEniQosGroupResponse
var err error
defer close(result)
response, err = client.CreateEniQosGroup(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// CreateEniQosGroupRequest is the request struct for api CreateEniQosGroup
type CreateEniQosGroupRequest struct {
*requests.RpcRequest
                    ResourceOwnerId     requests.Integer `position:"Query" name:"ResourceOwnerId"`
                    Tx     requests.Integer `position:"Query" name:"Tx"`
                    Rx     requests.Integer `position:"Query" name:"Rx"`
                    RxPps     requests.Integer `position:"Query" name:"RxPps"`
                    ResourceOwnerAccount     string `position:"Query" name:"ResourceOwnerAccount"`
                    OwnerId     requests.Integer `position:"Query" name:"OwnerId"`
                    QosGroupName     string `position:"Query" name:"QosGroupName"`
                    InstanceId     string `position:"Query" name:"InstanceId"`
                    TxPps     requests.Integer `position:"Query" name:"TxPps"`
}


// CreateEniQosGroupResponse is the response struct for api CreateEniQosGroup
type CreateEniQosGroupResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
            QosGroupName     string `json:"QosGroupName" xml:"QosGroupName"`
}

// CreateCreateEniQosGroupRequest creates a request to invoke CreateEniQosGroup API
func CreateCreateEniQosGroupRequest() (request *CreateEniQosGroupRequest) {
request = &CreateEniQosGroupRequest{
RpcRequest: &requests.RpcRequest{},
}
request.InitWithApiInfo("Ecs", "2016-03-14", "CreateEniQosGroup", "", "")
return
}

// CreateCreateEniQosGroupResponse creates a response to parse from CreateEniQosGroup response
func CreateCreateEniQosGroupResponse() (response *CreateEniQosGroupResponse) {
response = &CreateEniQosGroupResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


