
package ecs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// CreateSecurityGroup_GatedLaunch invokes the ecs.CreateSecurityGroup_GatedLaunch API synchronously
// api document: https://help.aliyun.com/api/ecs/createsecuritygroup_gatedlaunch.html
func (client *Client) CreateSecurityGroup_GatedLaunch(request *CreateSecurityGroup_GatedLaunchRequest) (response *CreateSecurityGroup_GatedLaunchResponse, err error) {
response = CreateCreateSecurityGroup_GatedLaunchResponse()
err = client.DoAction(request, response)
return
}

// CreateSecurityGroup_GatedLaunchWithChan invokes the ecs.CreateSecurityGroup_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/createsecuritygroup_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) CreateSecurityGroup_GatedLaunchWithChan(request *CreateSecurityGroup_GatedLaunchRequest) (<-chan *CreateSecurityGroup_GatedLaunchResponse, <-chan error) {
responseChan := make(chan *CreateSecurityGroup_GatedLaunchResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.CreateSecurityGroup_GatedLaunch(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// CreateSecurityGroup_GatedLaunchWithCallback invokes the ecs.CreateSecurityGroup_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/createsecuritygroup_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) CreateSecurityGroup_GatedLaunchWithCallback(request *CreateSecurityGroup_GatedLaunchRequest, callback func(response *CreateSecurityGroup_GatedLaunchResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *CreateSecurityGroup_GatedLaunchResponse
var err error
defer close(result)
response, err = client.CreateSecurityGroup_GatedLaunch(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// CreateSecurityGroup_GatedLaunchRequest is the request struct for api CreateSecurityGroup_GatedLaunch
type CreateSecurityGroup_GatedLaunchRequest struct {
*requests.RpcRequest
                    ResourceOwnerId     requests.Integer `position:"Query" name:"ResourceOwnerId"`
                    ClientToken     string `position:"Query" name:"ClientToken"`
                    Description     string `position:"Query" name:"Description"`
                    SecurityGroupName     string `position:"Query" name:"SecurityGroupName"`
                    Tag  *[]CreateSecurityGroup_GatedLaunchTag `position:"Query" name:"Tag"  type:"Repeated"`
                    ResourceOwnerAccount     string `position:"Query" name:"ResourceOwnerAccount"`
                    OwnerAccount     string `position:"Query" name:"OwnerAccount"`
                    OwnerId     requests.Integer `position:"Query" name:"OwnerId"`
                    VpcId     string `position:"Query" name:"VpcId"`
}

// CreateSecurityGroup_GatedLaunchTag is a repeated param struct in CreateSecurityGroup_GatedLaunchRequest
type CreateSecurityGroup_GatedLaunchTag struct{
        Value     string `name:"Value"`
        Key     string `name:"Key"`
}

// CreateSecurityGroup_GatedLaunchResponse is the response struct for api CreateSecurityGroup_GatedLaunch
type CreateSecurityGroup_GatedLaunchResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
            SecurityGroupId     string `json:"SecurityGroupId" xml:"SecurityGroupId"`
}

// CreateCreateSecurityGroup_GatedLaunchRequest creates a request to invoke CreateSecurityGroup_GatedLaunch API
func CreateCreateSecurityGroup_GatedLaunchRequest() (request *CreateSecurityGroup_GatedLaunchRequest) {
request = &CreateSecurityGroup_GatedLaunchRequest{
RpcRequest: &requests.RpcRequest{},
}
request.InitWithApiInfo("Ecs", "2014-05-26", "CreateSecurityGroup_GatedLaunch", "ecs", "openAPI")
return
}

// CreateCreateSecurityGroup_GatedLaunchResponse creates a response to parse from CreateSecurityGroup_GatedLaunch response
func CreateCreateSecurityGroup_GatedLaunchResponse() (response *CreateSecurityGroup_GatedLaunchResponse) {
response = &CreateSecurityGroup_GatedLaunchResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


