
package ecs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// DeleteVolume_GatedLaunch invokes the ecs.DeleteVolume_GatedLaunch API synchronously
// api document: https://help.aliyun.com/api/ecs/deletevolume_gatedlaunch.html
func (client *Client) DeleteVolume_GatedLaunch(request *DeleteVolume_GatedLaunchRequest) (response *DeleteVolume_GatedLaunchResponse, err error) {
response = CreateDeleteVolume_GatedLaunchResponse()
err = client.DoAction(request, response)
return
}

// DeleteVolume_GatedLaunchWithChan invokes the ecs.DeleteVolume_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/deletevolume_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) DeleteVolume_GatedLaunchWithChan(request *DeleteVolume_GatedLaunchRequest) (<-chan *DeleteVolume_GatedLaunchResponse, <-chan error) {
responseChan := make(chan *DeleteVolume_GatedLaunchResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.DeleteVolume_GatedLaunch(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// DeleteVolume_GatedLaunchWithCallback invokes the ecs.DeleteVolume_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/deletevolume_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) DeleteVolume_GatedLaunchWithCallback(request *DeleteVolume_GatedLaunchRequest, callback func(response *DeleteVolume_GatedLaunchResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *DeleteVolume_GatedLaunchResponse
var err error
defer close(result)
response, err = client.DeleteVolume_GatedLaunch(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// DeleteVolume_GatedLaunchRequest is the request struct for api DeleteVolume_GatedLaunch
type DeleteVolume_GatedLaunchRequest struct {
*requests.RpcRequest
                    ResourceOwnerId     requests.Integer `position:"Query" name:"ResourceOwnerId"`
                    ResourceOwnerAccount     string `position:"Query" name:"ResourceOwnerAccount"`
                    OwnerAccount     string `position:"Query" name:"OwnerAccount"`
                    OwnerId     requests.Integer `position:"Query" name:"OwnerId"`
                    VolumeId     string `position:"Query" name:"VolumeId"`
}


// DeleteVolume_GatedLaunchResponse is the response struct for api DeleteVolume_GatedLaunch
type DeleteVolume_GatedLaunchResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
}

// CreateDeleteVolume_GatedLaunchRequest creates a request to invoke DeleteVolume_GatedLaunch API
func CreateDeleteVolume_GatedLaunchRequest() (request *DeleteVolume_GatedLaunchRequest) {
request = &DeleteVolume_GatedLaunchRequest{
RpcRequest: &requests.RpcRequest{},
}
request.InitWithApiInfo("Ecs", "2014-05-26", "DeleteVolume_GatedLaunch", "ecs", "openAPI")
return
}

// CreateDeleteVolume_GatedLaunchResponse creates a response to parse from DeleteVolume_GatedLaunch response
func CreateDeleteVolume_GatedLaunchResponse() (response *DeleteVolume_GatedLaunchResponse) {
response = &DeleteVolume_GatedLaunchResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


