
package ecs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// DeleteSnapshot_GatedLaunch invokes the ecs.DeleteSnapshot_GatedLaunch API synchronously
// api document: https://help.aliyun.com/api/ecs/deletesnapshot_gatedlaunch.html
func (client *Client) DeleteSnapshot_GatedLaunch(request *DeleteSnapshot_GatedLaunchRequest) (response *DeleteSnapshot_GatedLaunchResponse, err error) {
response = CreateDeleteSnapshot_GatedLaunchResponse()
err = client.DoAction(request, response)
return
}

// DeleteSnapshot_GatedLaunchWithChan invokes the ecs.DeleteSnapshot_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/deletesnapshot_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) DeleteSnapshot_GatedLaunchWithChan(request *DeleteSnapshot_GatedLaunchRequest) (<-chan *DeleteSnapshot_GatedLaunchResponse, <-chan error) {
responseChan := make(chan *DeleteSnapshot_GatedLaunchResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.DeleteSnapshot_GatedLaunch(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// DeleteSnapshot_GatedLaunchWithCallback invokes the ecs.DeleteSnapshot_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/deletesnapshot_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) DeleteSnapshot_GatedLaunchWithCallback(request *DeleteSnapshot_GatedLaunchRequest, callback func(response *DeleteSnapshot_GatedLaunchResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *DeleteSnapshot_GatedLaunchResponse
var err error
defer close(result)
response, err = client.DeleteSnapshot_GatedLaunch(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// DeleteSnapshot_GatedLaunchRequest is the request struct for api DeleteSnapshot_GatedLaunch
type DeleteSnapshot_GatedLaunchRequest struct {
*requests.RpcRequest
                    ResourceOwnerId     requests.Integer `position:"Query" name:"ResourceOwnerId"`
                    SnapshotId     string `position:"Query" name:"SnapshotId"`
                    ResourceOwnerAccount     string `position:"Query" name:"ResourceOwnerAccount"`
                    OwnerAccount     string `position:"Query" name:"OwnerAccount"`
                    OwnerId     requests.Integer `position:"Query" name:"OwnerId"`
}


// DeleteSnapshot_GatedLaunchResponse is the response struct for api DeleteSnapshot_GatedLaunch
type DeleteSnapshot_GatedLaunchResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
}

// CreateDeleteSnapshot_GatedLaunchRequest creates a request to invoke DeleteSnapshot_GatedLaunch API
func CreateDeleteSnapshot_GatedLaunchRequest() (request *DeleteSnapshot_GatedLaunchRequest) {
request = &DeleteSnapshot_GatedLaunchRequest{
RpcRequest: &requests.RpcRequest{},
}
request.InitWithApiInfo("Ecs", "2014-05-26", "DeleteSnapshot_GatedLaunch", "", "")
return
}

// CreateDeleteSnapshot_GatedLaunchResponse creates a response to parse from DeleteSnapshot_GatedLaunch response
func CreateDeleteSnapshot_GatedLaunchResponse() (response *DeleteSnapshot_GatedLaunchResponse) {
response = &DeleteSnapshot_GatedLaunchResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


