
package ecs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// DescribeInstanceVncUrl_GatedLaunch invokes the ecs.DescribeInstanceVncUrl_GatedLaunch API synchronously
// api document: https://help.aliyun.com/api/ecs/describeinstancevncurl_gatedlaunch.html
func (client *Client) DescribeInstanceVncUrl_GatedLaunch(request *DescribeInstanceVncUrl_GatedLaunchRequest) (response *DescribeInstanceVncUrl_GatedLaunchResponse, err error) {
response = CreateDescribeInstanceVncUrl_GatedLaunchResponse()
err = client.DoAction(request, response)
return
}

// DescribeInstanceVncUrl_GatedLaunchWithChan invokes the ecs.DescribeInstanceVncUrl_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/describeinstancevncurl_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) DescribeInstanceVncUrl_GatedLaunchWithChan(request *DescribeInstanceVncUrl_GatedLaunchRequest) (<-chan *DescribeInstanceVncUrl_GatedLaunchResponse, <-chan error) {
responseChan := make(chan *DescribeInstanceVncUrl_GatedLaunchResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.DescribeInstanceVncUrl_GatedLaunch(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// DescribeInstanceVncUrl_GatedLaunchWithCallback invokes the ecs.DescribeInstanceVncUrl_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/describeinstancevncurl_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) DescribeInstanceVncUrl_GatedLaunchWithCallback(request *DescribeInstanceVncUrl_GatedLaunchRequest, callback func(response *DescribeInstanceVncUrl_GatedLaunchResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *DescribeInstanceVncUrl_GatedLaunchResponse
var err error
defer close(result)
response, err = client.DescribeInstanceVncUrl_GatedLaunch(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// DescribeInstanceVncUrl_GatedLaunchRequest is the request struct for api DescribeInstanceVncUrl_GatedLaunch
type DescribeInstanceVncUrl_GatedLaunchRequest struct {
*requests.RpcRequest
                    ResourceOwnerId     requests.Integer `position:"Query" name:"ResourceOwnerId"`
                    ResourceOwnerAccount     string `position:"Query" name:"ResourceOwnerAccount"`
                    OwnerAccount     string `position:"Query" name:"OwnerAccount"`
                    OwnerId     requests.Integer `position:"Query" name:"OwnerId"`
                    InstanceId     string `position:"Query" name:"InstanceId"`
}


// DescribeInstanceVncUrl_GatedLaunchResponse is the response struct for api DescribeInstanceVncUrl_GatedLaunch
type DescribeInstanceVncUrl_GatedLaunchResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
            VncUrl     string `json:"VncUrl" xml:"VncUrl"`
}

// CreateDescribeInstanceVncUrl_GatedLaunchRequest creates a request to invoke DescribeInstanceVncUrl_GatedLaunch API
func CreateDescribeInstanceVncUrl_GatedLaunchRequest() (request *DescribeInstanceVncUrl_GatedLaunchRequest) {
request = &DescribeInstanceVncUrl_GatedLaunchRequest{
RpcRequest: &requests.RpcRequest{},
}
request.InitWithApiInfo("Ecs", "2014-05-26", "DescribeInstanceVncUrl_GatedLaunch", "", "")
return
}

// CreateDescribeInstanceVncUrl_GatedLaunchResponse creates a response to parse from DescribeInstanceVncUrl_GatedLaunch response
func CreateDescribeInstanceVncUrl_GatedLaunchResponse() (response *DescribeInstanceVncUrl_GatedLaunchResponse) {
response = &DescribeInstanceVncUrl_GatedLaunchResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


