package ecs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// DescribeBandwidthSpec invokes the ecs.DescribeBandwidthSpec API synchronously
func (client *Client) DescribeBandwidthSpec(request *DescribeBandwidthSpecRequest) (response *DescribeBandwidthSpecResponse, err error) {
	response = CreateDescribeBandwidthSpecResponse()
	err = client.DoAction(request, response)
	return
}

// DescribeBandwidthSpecWithChan invokes the ecs.DescribeBandwidthSpec API asynchronously
func (client *Client) DescribeBandwidthSpecWithChan(request *DescribeBandwidthSpecRequest) (<-chan *DescribeBandwidthSpecResponse, <-chan error) {
	responseChan := make(chan *DescribeBandwidthSpecResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.DescribeBandwidthSpec(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// DescribeBandwidthSpecWithCallback invokes the ecs.DescribeBandwidthSpec API asynchronously
func (client *Client) DescribeBandwidthSpecWithCallback(request *DescribeBandwidthSpecRequest, callback func(response *DescribeBandwidthSpecResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *DescribeBandwidthSpecResponse
		var err error
		defer close(result)
		response, err = client.DescribeBandwidthSpec(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// DescribeBandwidthSpecRequest is the request struct for api DescribeBandwidthSpec
type DescribeBandwidthSpecRequest struct {
	*requests.RpcRequest
	ResourceOwnerId      requests.Integer `position:"Query" name:"ResourceOwnerId"`
	InstanceType         string           `position:"Query" name:"InstanceType"`
	ResourceOwnerAccount string           `position:"Query" name:"ResourceOwnerAccount"`
	OwnerAccount         string           `position:"Query" name:"OwnerAccount"`
	OwnerId              requests.Integer `position:"Query" name:"OwnerId"`
	SaleStrategy         string           `position:"Query" name:"SaleStrategy"`
}

// DescribeBandwidthSpecResponse is the response struct for api DescribeBandwidthSpec
type DescribeBandwidthSpecResponse struct {
	*responses.BaseResponse
	RequestId  string                            `json:"RequestId" xml:"RequestId"`
	Bandwidths BandwidthsInDescribeBandwidthSpec `json:"Bandwidths" xml:"Bandwidths"`
}

// CreateDescribeBandwidthSpecRequest creates a request to invoke DescribeBandwidthSpec API
func CreateDescribeBandwidthSpecRequest() (request *DescribeBandwidthSpecRequest) {
	request = &DescribeBandwidthSpecRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("Ecs", "2014-05-26", "DescribeBandwidthSpec", "ecs", "openAPI")
	request.Method = requests.POST
	return
}

// CreateDescribeBandwidthSpecResponse creates a response to parse from DescribeBandwidthSpec response
func CreateDescribeBandwidthSpecResponse() (response *DescribeBandwidthSpecResponse) {
	response = &DescribeBandwidthSpecResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
