
package ecs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// DescribeIntranetAttributeKb_GatedLaunch invokes the ecs.DescribeIntranetAttributeKb_GatedLaunch API synchronously
// api document: https://help.aliyun.com/api/ecs/describeintranetattributekb_gatedlaunch.html
func (client *Client) DescribeIntranetAttributeKb_GatedLaunch(request *DescribeIntranetAttributeKb_GatedLaunchRequest) (response *DescribeIntranetAttributeKb_GatedLaunchResponse, err error) {
response = CreateDescribeIntranetAttributeKb_GatedLaunchResponse()
err = client.DoAction(request, response)
return
}

// DescribeIntranetAttributeKb_GatedLaunchWithChan invokes the ecs.DescribeIntranetAttributeKb_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/describeintranetattributekb_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) DescribeIntranetAttributeKb_GatedLaunchWithChan(request *DescribeIntranetAttributeKb_GatedLaunchRequest) (<-chan *DescribeIntranetAttributeKb_GatedLaunchResponse, <-chan error) {
responseChan := make(chan *DescribeIntranetAttributeKb_GatedLaunchResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.DescribeIntranetAttributeKb_GatedLaunch(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// DescribeIntranetAttributeKb_GatedLaunchWithCallback invokes the ecs.DescribeIntranetAttributeKb_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/describeintranetattributekb_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) DescribeIntranetAttributeKb_GatedLaunchWithCallback(request *DescribeIntranetAttributeKb_GatedLaunchRequest, callback func(response *DescribeIntranetAttributeKb_GatedLaunchResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *DescribeIntranetAttributeKb_GatedLaunchResponse
var err error
defer close(result)
response, err = client.DescribeIntranetAttributeKb_GatedLaunch(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// DescribeIntranetAttributeKb_GatedLaunchRequest is the request struct for api DescribeIntranetAttributeKb_GatedLaunch
type DescribeIntranetAttributeKb_GatedLaunchRequest struct {
*requests.RpcRequest
                    ResourceOwnerId     requests.Integer `position:"Query" name:"ResourceOwnerId"`
                    ResourceOwnerAccount     string `position:"Query" name:"ResourceOwnerAccount"`
                    OwnerAccount     string `position:"Query" name:"OwnerAccount"`
                    OwnerId     requests.Integer `position:"Query" name:"OwnerId"`
                    InstanceId     string `position:"Query" name:"InstanceId"`
}


// DescribeIntranetAttributeKb_GatedLaunchResponse is the response struct for api DescribeIntranetAttributeKb_GatedLaunch
type DescribeIntranetAttributeKb_GatedLaunchResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
            InstanceId     string `json:"InstanceId" xml:"InstanceId"`
            VlanId     string `json:"VlanId" xml:"VlanId"`
            IntranetIpAddress     string `json:"IntranetIpAddress" xml:"IntranetIpAddress"`
            IntranetMaxBandwidthIn     int `json:"IntranetMaxBandwidthIn" xml:"IntranetMaxBandwidthIn"`
            IntranetMaxBandwidthOut     int `json:"IntranetMaxBandwidthOut" xml:"IntranetMaxBandwidthOut"`
}

// CreateDescribeIntranetAttributeKb_GatedLaunchRequest creates a request to invoke DescribeIntranetAttributeKb_GatedLaunch API
func CreateDescribeIntranetAttributeKb_GatedLaunchRequest() (request *DescribeIntranetAttributeKb_GatedLaunchRequest) {
request = &DescribeIntranetAttributeKb_GatedLaunchRequest{
RpcRequest: &requests.RpcRequest{},
}
request.InitWithApiInfo("Ecs", "2014-05-26", "DescribeIntranetAttributeKb_GatedLaunch", "", "")
return
}

// CreateDescribeIntranetAttributeKb_GatedLaunchResponse creates a response to parse from DescribeIntranetAttributeKb_GatedLaunch response
func CreateDescribeIntranetAttributeKb_GatedLaunchResponse() (response *DescribeIntranetAttributeKb_GatedLaunchResponse) {
response = &DescribeIntranetAttributeKb_GatedLaunchResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


