
package ecs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// ExportImage_GatedLaunch invokes the ecs.ExportImage_GatedLaunch API synchronously
// api document: https://help.aliyun.com/api/ecs/exportimage_gatedlaunch.html
func (client *Client) ExportImage_GatedLaunch(request *ExportImage_GatedLaunchRequest) (response *ExportImage_GatedLaunchResponse, err error) {
response = CreateExportImage_GatedLaunchResponse()
err = client.DoAction(request, response)
return
}

// ExportImage_GatedLaunchWithChan invokes the ecs.ExportImage_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/exportimage_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) ExportImage_GatedLaunchWithChan(request *ExportImage_GatedLaunchRequest) (<-chan *ExportImage_GatedLaunchResponse, <-chan error) {
responseChan := make(chan *ExportImage_GatedLaunchResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.ExportImage_GatedLaunch(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// ExportImage_GatedLaunchWithCallback invokes the ecs.ExportImage_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/exportimage_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) ExportImage_GatedLaunchWithCallback(request *ExportImage_GatedLaunchRequest, callback func(response *ExportImage_GatedLaunchResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *ExportImage_GatedLaunchResponse
var err error
defer close(result)
response, err = client.ExportImage_GatedLaunch(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// ExportImage_GatedLaunchRequest is the request struct for api ExportImage_GatedLaunch
type ExportImage_GatedLaunchRequest struct {
*requests.RpcRequest
                    ResourceOwnerId     requests.Integer `position:"Query" name:"ResourceOwnerId"`
                    ImageId     string `position:"Query" name:"ImageId"`
                    OSSBucket     string `position:"Query" name:"OSSBucket"`
                    ResourceOwnerAccount     string `position:"Query" name:"ResourceOwnerAccount"`
                    RoleName     string `position:"Query" name:"RoleName"`
                    OwnerId     requests.Integer `position:"Query" name:"OwnerId"`
                    OSSPrefix     string `position:"Query" name:"OSSPrefix"`
                    ImageFormat     string `position:"Query" name:"ImageFormat"`
}


// ExportImage_GatedLaunchResponse is the response struct for api ExportImage_GatedLaunch
type ExportImage_GatedLaunchResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
            TaskId     string `json:"TaskId" xml:"TaskId"`
            RegionId     string `json:"RegionId" xml:"RegionId"`
}

// CreateExportImage_GatedLaunchRequest creates a request to invoke ExportImage_GatedLaunch API
func CreateExportImage_GatedLaunchRequest() (request *ExportImage_GatedLaunchRequest) {
request = &ExportImage_GatedLaunchRequest{
RpcRequest: &requests.RpcRequest{},
}
request.InitWithApiInfo("Ecs", "2014-05-26", "ExportImage_GatedLaunch", "", "")
return
}

// CreateExportImage_GatedLaunchResponse creates a response to parse from ExportImage_GatedLaunch response
func CreateExportImage_GatedLaunchResponse() (response *ExportImage_GatedLaunchResponse) {
response = &ExportImage_GatedLaunchResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


