
package ecs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// ModifyImageAttribute_GatedLaunch invokes the ecs.ModifyImageAttribute_GatedLaunch API synchronously
// api document: https://help.aliyun.com/api/ecs/modifyimageattribute_gatedlaunch.html
func (client *Client) ModifyImageAttribute_GatedLaunch(request *ModifyImageAttribute_GatedLaunchRequest) (response *ModifyImageAttribute_GatedLaunchResponse, err error) {
response = CreateModifyImageAttribute_GatedLaunchResponse()
err = client.DoAction(request, response)
return
}

// ModifyImageAttribute_GatedLaunchWithChan invokes the ecs.ModifyImageAttribute_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/modifyimageattribute_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) ModifyImageAttribute_GatedLaunchWithChan(request *ModifyImageAttribute_GatedLaunchRequest) (<-chan *ModifyImageAttribute_GatedLaunchResponse, <-chan error) {
responseChan := make(chan *ModifyImageAttribute_GatedLaunchResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.ModifyImageAttribute_GatedLaunch(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// ModifyImageAttribute_GatedLaunchWithCallback invokes the ecs.ModifyImageAttribute_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/modifyimageattribute_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) ModifyImageAttribute_GatedLaunchWithCallback(request *ModifyImageAttribute_GatedLaunchRequest, callback func(response *ModifyImageAttribute_GatedLaunchResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *ModifyImageAttribute_GatedLaunchResponse
var err error
defer close(result)
response, err = client.ModifyImageAttribute_GatedLaunch(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// ModifyImageAttribute_GatedLaunchRequest is the request struct for api ModifyImageAttribute_GatedLaunch
type ModifyImageAttribute_GatedLaunchRequest struct {
*requests.RpcRequest
                    ResourceOwnerId     requests.Integer `position:"Query" name:"ResourceOwnerId"`
                    ImageId     string `position:"Query" name:"ImageId"`
                    Description     string `position:"Query" name:"Description"`
                    ImageName     string `position:"Query" name:"ImageName"`
                    ResourceOwnerAccount     string `position:"Query" name:"ResourceOwnerAccount"`
                    OwnerAccount     string `position:"Query" name:"OwnerAccount"`
                    OwnerId     requests.Integer `position:"Query" name:"OwnerId"`
}


// ModifyImageAttribute_GatedLaunchResponse is the response struct for api ModifyImageAttribute_GatedLaunch
type ModifyImageAttribute_GatedLaunchResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
}

// CreateModifyImageAttribute_GatedLaunchRequest creates a request to invoke ModifyImageAttribute_GatedLaunch API
func CreateModifyImageAttribute_GatedLaunchRequest() (request *ModifyImageAttribute_GatedLaunchRequest) {
request = &ModifyImageAttribute_GatedLaunchRequest{
RpcRequest: &requests.RpcRequest{},
}
request.InitWithApiInfo("Ecs", "2014-05-26", "ModifyImageAttribute_GatedLaunch", "ecs", "openAPI")
return
}

// CreateModifyImageAttribute_GatedLaunchResponse creates a response to parse from ModifyImageAttribute_GatedLaunch response
func CreateModifyImageAttribute_GatedLaunchResponse() (response *ModifyImageAttribute_GatedLaunchResponse) {
response = &ModifyImageAttribute_GatedLaunchResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


