package ecs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// ModifyElasticProtection invokes the ecs.ModifyElasticProtection API synchronously
func (client *Client) ModifyElasticProtection(request *ModifyElasticProtectionRequest) (response *ModifyElasticProtectionResponse, err error) {
	response = CreateModifyElasticProtectionResponse()
	err = client.DoAction(request, response)
	return
}

// ModifyElasticProtectionWithChan invokes the ecs.ModifyElasticProtection API asynchronously
func (client *Client) ModifyElasticProtectionWithChan(request *ModifyElasticProtectionRequest) (<-chan *ModifyElasticProtectionResponse, <-chan error) {
	responseChan := make(chan *ModifyElasticProtectionResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.ModifyElasticProtection(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// ModifyElasticProtectionWithCallback invokes the ecs.ModifyElasticProtection API asynchronously
func (client *Client) ModifyElasticProtectionWithCallback(request *ModifyElasticProtectionRequest, callback func(response *ModifyElasticProtectionResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *ModifyElasticProtectionResponse
		var err error
		defer close(result)
		response, err = client.ModifyElasticProtection(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// ModifyElasticProtectionRequest is the request struct for api ModifyElasticProtection
type ModifyElasticProtectionRequest struct {
	*requests.RpcRequest
	ResourceOwnerId      requests.Integer `position:"Query" name:"ResourceOwnerId"`
	InstanceTypes        *[]string        `position:"Query" name:"InstanceTypes"  type:"Repeated"`
	Description          string           `position:"Query" name:"Description"`
	StartTime            string           `position:"Query" name:"StartTime"`
	Platform             string           `position:"Query" name:"Platform"`
	ZoneIds              *[]string        `position:"Query" name:"ZoneIds"  type:"Repeated"`
	PageSize             requests.Integer `position:"Query" name:"PageSize"`
	InstanceChargeType   string           `position:"Query" name:"InstanceChargeType"`
	ProtectionTimes      string           `position:"Query" name:"ProtectionTimes"`
	ResourceOwnerAccount string           `position:"Query" name:"ResourceOwnerAccount"`
	OwnerAccount         string           `position:"Query" name:"OwnerAccount"`
	ElasticProtectionId  string           `position:"Query" name:"ElasticProtectionId"`
	OwnerId              requests.Integer `position:"Query" name:"OwnerId"`
	InstanceEligibility  string           `position:"Query" name:"InstanceEligibility"`
	Name                 string           `position:"Query" name:"Name"`
	PackageType          string           `position:"Query" name:"PackageType"`
	ResourceAmount       string           `position:"Query" name:"ResourceAmount"`
}

// ModifyElasticProtectionResponse is the response struct for api ModifyElasticProtection
type ModifyElasticProtectionResponse struct {
	*responses.BaseResponse
	RequestId string `json:"RequestId" xml:"RequestId"`
}

// CreateModifyElasticProtectionRequest creates a request to invoke ModifyElasticProtection API
func CreateModifyElasticProtectionRequest() (request *ModifyElasticProtectionRequest) {
	request = &ModifyElasticProtectionRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("Ecs", "2014-05-26", "ModifyElasticProtection", "ecs", "openAPI")
	request.Method = requests.POST
	return
}

// CreateModifyElasticProtectionResponse creates a response to parse from ModifyElasticProtection response
func CreateModifyElasticProtectionResponse() (response *ModifyElasticProtectionResponse) {
	response = &ModifyElasticProtectionResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
