
package ecs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// ModifyAutoSnapshotPolicyEx_GatedLaunch invokes the ecs.ModifyAutoSnapshotPolicyEx_GatedLaunch API synchronously
// api document: https://help.aliyun.com/api/ecs/modifyautosnapshotpolicyex_gatedlaunch.html
func (client *Client) ModifyAutoSnapshotPolicyEx_GatedLaunch(request *ModifyAutoSnapshotPolicyEx_GatedLaunchRequest) (response *ModifyAutoSnapshotPolicyEx_GatedLaunchResponse, err error) {
response = CreateModifyAutoSnapshotPolicyEx_GatedLaunchResponse()
err = client.DoAction(request, response)
return
}

// ModifyAutoSnapshotPolicyEx_GatedLaunchWithChan invokes the ecs.ModifyAutoSnapshotPolicyEx_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/modifyautosnapshotpolicyex_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) ModifyAutoSnapshotPolicyEx_GatedLaunchWithChan(request *ModifyAutoSnapshotPolicyEx_GatedLaunchRequest) (<-chan *ModifyAutoSnapshotPolicyEx_GatedLaunchResponse, <-chan error) {
responseChan := make(chan *ModifyAutoSnapshotPolicyEx_GatedLaunchResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.ModifyAutoSnapshotPolicyEx_GatedLaunch(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// ModifyAutoSnapshotPolicyEx_GatedLaunchWithCallback invokes the ecs.ModifyAutoSnapshotPolicyEx_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/modifyautosnapshotpolicyex_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) ModifyAutoSnapshotPolicyEx_GatedLaunchWithCallback(request *ModifyAutoSnapshotPolicyEx_GatedLaunchRequest, callback func(response *ModifyAutoSnapshotPolicyEx_GatedLaunchResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *ModifyAutoSnapshotPolicyEx_GatedLaunchResponse
var err error
defer close(result)
response, err = client.ModifyAutoSnapshotPolicyEx_GatedLaunch(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// ModifyAutoSnapshotPolicyEx_GatedLaunchRequest is the request struct for api ModifyAutoSnapshotPolicyEx_GatedLaunch
type ModifyAutoSnapshotPolicyEx_GatedLaunchRequest struct {
*requests.RpcRequest
                    ResourceOwnerId     requests.Integer `position:"Query" name:"ResourceOwnerId"`
                    AutoSnapshotPolicyId     string `position:"Query" name:"autoSnapshotPolicyId"`
                    TimePoints     string `position:"Query" name:"timePoints"`
                    RepeatWeekdays     string `position:"Query" name:"repeatWeekdays"`
                    ResourceOwnerAccount     string `position:"Query" name:"ResourceOwnerAccount"`
                    OwnerId     requests.Integer `position:"Query" name:"OwnerId"`
                    AutoSnapshotPolicyName     string `position:"Query" name:"autoSnapshotPolicyName"`
                    RetentionDays     requests.Integer `position:"Query" name:"retentionDays"`
}


// ModifyAutoSnapshotPolicyEx_GatedLaunchResponse is the response struct for api ModifyAutoSnapshotPolicyEx_GatedLaunch
type ModifyAutoSnapshotPolicyEx_GatedLaunchResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
}

// CreateModifyAutoSnapshotPolicyEx_GatedLaunchRequest creates a request to invoke ModifyAutoSnapshotPolicyEx_GatedLaunch API
func CreateModifyAutoSnapshotPolicyEx_GatedLaunchRequest() (request *ModifyAutoSnapshotPolicyEx_GatedLaunchRequest) {
request = &ModifyAutoSnapshotPolicyEx_GatedLaunchRequest{
RpcRequest: &requests.RpcRequest{},
}
request.InitWithApiInfo("Ecs", "2014-05-26", "ModifyAutoSnapshotPolicyEx_GatedLaunch", "", "")
return
}

// CreateModifyAutoSnapshotPolicyEx_GatedLaunchResponse creates a response to parse from ModifyAutoSnapshotPolicyEx_GatedLaunch response
func CreateModifyAutoSnapshotPolicyEx_GatedLaunchResponse() (response *ModifyAutoSnapshotPolicyEx_GatedLaunchResponse) {
response = &ModifyAutoSnapshotPolicyEx_GatedLaunchResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


