
package ecs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// ModifySnapshotAttribute_GatedLaunch invokes the ecs.ModifySnapshotAttribute_GatedLaunch API synchronously
// api document: https://help.aliyun.com/api/ecs/modifysnapshotattribute_gatedlaunch.html
func (client *Client) ModifySnapshotAttribute_GatedLaunch(request *ModifySnapshotAttribute_GatedLaunchRequest) (response *ModifySnapshotAttribute_GatedLaunchResponse, err error) {
response = CreateModifySnapshotAttribute_GatedLaunchResponse()
err = client.DoAction(request, response)
return
}

// ModifySnapshotAttribute_GatedLaunchWithChan invokes the ecs.ModifySnapshotAttribute_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/modifysnapshotattribute_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) ModifySnapshotAttribute_GatedLaunchWithChan(request *ModifySnapshotAttribute_GatedLaunchRequest) (<-chan *ModifySnapshotAttribute_GatedLaunchResponse, <-chan error) {
responseChan := make(chan *ModifySnapshotAttribute_GatedLaunchResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.ModifySnapshotAttribute_GatedLaunch(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// ModifySnapshotAttribute_GatedLaunchWithCallback invokes the ecs.ModifySnapshotAttribute_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/modifysnapshotattribute_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) ModifySnapshotAttribute_GatedLaunchWithCallback(request *ModifySnapshotAttribute_GatedLaunchRequest, callback func(response *ModifySnapshotAttribute_GatedLaunchResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *ModifySnapshotAttribute_GatedLaunchResponse
var err error
defer close(result)
response, err = client.ModifySnapshotAttribute_GatedLaunch(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// ModifySnapshotAttribute_GatedLaunchRequest is the request struct for api ModifySnapshotAttribute_GatedLaunch
type ModifySnapshotAttribute_GatedLaunchRequest struct {
*requests.RpcRequest
                    ResourceOwnerId     requests.Integer `position:"Query" name:"ResourceOwnerId"`
                    SnapshotId     string `position:"Query" name:"SnapshotId"`
                    Description     string `position:"Query" name:"Description"`
                    SnapshotName     string `position:"Query" name:"SnapshotName"`
                    ResourceOwnerAccount     string `position:"Query" name:"ResourceOwnerAccount"`
                    OwnerAccount     string `position:"Query" name:"OwnerAccount"`
                    OwnerId     requests.Integer `position:"Query" name:"OwnerId"`
}


// ModifySnapshotAttribute_GatedLaunchResponse is the response struct for api ModifySnapshotAttribute_GatedLaunch
type ModifySnapshotAttribute_GatedLaunchResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
}

// CreateModifySnapshotAttribute_GatedLaunchRequest creates a request to invoke ModifySnapshotAttribute_GatedLaunch API
func CreateModifySnapshotAttribute_GatedLaunchRequest() (request *ModifySnapshotAttribute_GatedLaunchRequest) {
request = &ModifySnapshotAttribute_GatedLaunchRequest{
RpcRequest: &requests.RpcRequest{},
}
request.InitWithApiInfo("Ecs", "2014-05-26", "ModifySnapshotAttribute_GatedLaunch", "ecs", "openAPI")
return
}

// CreateModifySnapshotAttribute_GatedLaunchResponse creates a response to parse from ModifySnapshotAttribute_GatedLaunch response
func CreateModifySnapshotAttribute_GatedLaunchResponse() (response *ModifySnapshotAttribute_GatedLaunchResponse) {
response = &ModifySnapshotAttribute_GatedLaunchResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


