
package ecs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// ModifyInstanceSpec_GatedLaunch invokes the ecs.ModifyInstanceSpec_GatedLaunch API synchronously
// api document: https://help.aliyun.com/api/ecs/modifyinstancespec_gatedlaunch.html
func (client *Client) ModifyInstanceSpec_GatedLaunch(request *ModifyInstanceSpec_GatedLaunchRequest) (response *ModifyInstanceSpec_GatedLaunchResponse, err error) {
response = CreateModifyInstanceSpec_GatedLaunchResponse()
err = client.DoAction(request, response)
return
}

// ModifyInstanceSpec_GatedLaunchWithChan invokes the ecs.ModifyInstanceSpec_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/modifyinstancespec_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) ModifyInstanceSpec_GatedLaunchWithChan(request *ModifyInstanceSpec_GatedLaunchRequest) (<-chan *ModifyInstanceSpec_GatedLaunchResponse, <-chan error) {
responseChan := make(chan *ModifyInstanceSpec_GatedLaunchResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.ModifyInstanceSpec_GatedLaunch(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// ModifyInstanceSpec_GatedLaunchWithCallback invokes the ecs.ModifyInstanceSpec_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/modifyinstancespec_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) ModifyInstanceSpec_GatedLaunchWithCallback(request *ModifyInstanceSpec_GatedLaunchRequest, callback func(response *ModifyInstanceSpec_GatedLaunchResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *ModifyInstanceSpec_GatedLaunchResponse
var err error
defer close(result)
response, err = client.ModifyInstanceSpec_GatedLaunch(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// ModifyInstanceSpec_GatedLaunchRequest is the request struct for api ModifyInstanceSpec_GatedLaunch
type ModifyInstanceSpec_GatedLaunchRequest struct {
*requests.RpcRequest
                    ResourceOwnerId     requests.Integer `position:"Query" name:"ResourceOwnerId"`
                    InternetMaxBandwidthOut     requests.Integer `position:"Query" name:"InternetMaxBandwidthOut"`
                    InstanceType     string `position:"Query" name:"InstanceType"`
                    TemporaryEndTime     string `position:"Query" name:"Temporary.EndTime"`
                    ResourceOwnerAccount     string `position:"Query" name:"ResourceOwnerAccount"`
                    OwnerAccount     string `position:"Query" name:"OwnerAccount"`
                    OwnerId     requests.Integer `position:"Query" name:"OwnerId"`
                    TemporaryInternetMaxBandwidthOut     requests.Integer `position:"Query" name:"Temporary.InternetMaxBandwidthOut"`
                    TemporaryStartTime     string `position:"Query" name:"Temporary.StartTime"`
                    Async     requests.Boolean `position:"Query" name:"Async"`
                    InstanceId     string `position:"Query" name:"InstanceId"`
                    InternetMaxBandwidthIn     requests.Integer `position:"Query" name:"InternetMaxBandwidthIn"`
}


// ModifyInstanceSpec_GatedLaunchResponse is the response struct for api ModifyInstanceSpec_GatedLaunch
type ModifyInstanceSpec_GatedLaunchResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
}

// CreateModifyInstanceSpec_GatedLaunchRequest creates a request to invoke ModifyInstanceSpec_GatedLaunch API
func CreateModifyInstanceSpec_GatedLaunchRequest() (request *ModifyInstanceSpec_GatedLaunchRequest) {
request = &ModifyInstanceSpec_GatedLaunchRequest{
RpcRequest: &requests.RpcRequest{},
}
request.InitWithApiInfo("Ecs", "2014-05-26", "ModifyInstanceSpec_GatedLaunch", "", "")
return
}

// CreateModifyInstanceSpec_GatedLaunchResponse creates a response to parse from ModifyInstanceSpec_GatedLaunch response
func CreateModifyInstanceSpec_GatedLaunchResponse() (response *ModifyInstanceSpec_GatedLaunchResponse) {
response = &ModifyInstanceSpec_GatedLaunchResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


