
package ecs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// RemoveTags_GatedLaunch invokes the ecs.RemoveTags_GatedLaunch API synchronously
// api document: https://help.aliyun.com/api/ecs/removetags_gatedlaunch.html
func (client *Client) RemoveTags_GatedLaunch(request *RemoveTags_GatedLaunchRequest) (response *RemoveTags_GatedLaunchResponse, err error) {
response = CreateRemoveTags_GatedLaunchResponse()
err = client.DoAction(request, response)
return
}

// RemoveTags_GatedLaunchWithChan invokes the ecs.RemoveTags_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/removetags_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) RemoveTags_GatedLaunchWithChan(request *RemoveTags_GatedLaunchRequest) (<-chan *RemoveTags_GatedLaunchResponse, <-chan error) {
responseChan := make(chan *RemoveTags_GatedLaunchResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.RemoveTags_GatedLaunch(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// RemoveTags_GatedLaunchWithCallback invokes the ecs.RemoveTags_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/removetags_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) RemoveTags_GatedLaunchWithCallback(request *RemoveTags_GatedLaunchRequest, callback func(response *RemoveTags_GatedLaunchResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *RemoveTags_GatedLaunchResponse
var err error
defer close(result)
response, err = client.RemoveTags_GatedLaunch(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// RemoveTags_GatedLaunchRequest is the request struct for api RemoveTags_GatedLaunch
type RemoveTags_GatedLaunchRequest struct {
*requests.RpcRequest
                    ResourceOwnerId     requests.Integer `position:"Query" name:"ResourceOwnerId"`
                    Tag  *[]RemoveTags_GatedLaunchTag `position:"Query" name:"Tag"  type:"Repeated"`
                    ResourceId     string `position:"Query" name:"ResourceId"`
                    ResourceOwnerAccount     string `position:"Query" name:"ResourceOwnerAccount"`
                    OwnerId     requests.Integer `position:"Query" name:"OwnerId"`
                    ResourceType     string `position:"Query" name:"ResourceType"`
}

// RemoveTags_GatedLaunchTag is a repeated param struct in RemoveTags_GatedLaunchRequest
type RemoveTags_GatedLaunchTag struct{
        Value     string `name:"Value"`
        Key     string `name:"Key"`
}

// RemoveTags_GatedLaunchResponse is the response struct for api RemoveTags_GatedLaunch
type RemoveTags_GatedLaunchResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
}

// CreateRemoveTags_GatedLaunchRequest creates a request to invoke RemoveTags_GatedLaunch API
func CreateRemoveTags_GatedLaunchRequest() (request *RemoveTags_GatedLaunchRequest) {
request = &RemoveTags_GatedLaunchRequest{
RpcRequest: &requests.RpcRequest{},
}
request.InitWithApiInfo("Ecs", "2014-05-26", "RemoveTags_GatedLaunch", "ecs", "openAPI")
return
}

// CreateRemoveTags_GatedLaunchResponse creates a response to parse from RemoveTags_GatedLaunch response
func CreateRemoveTags_GatedLaunchResponse() (response *RemoveTags_GatedLaunchResponse) {
response = &RemoveTags_GatedLaunchResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


