package ecs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// RenameManagedInstance invokes the ecs.RenameManagedInstance API synchronously
func (client *Client) RenameManagedInstance(request *RenameManagedInstanceRequest) (response *RenameManagedInstanceResponse, err error) {
	response = CreateRenameManagedInstanceResponse()
	err = client.DoAction(request, response)
	return
}

// RenameManagedInstanceWithChan invokes the ecs.RenameManagedInstance API asynchronously
func (client *Client) RenameManagedInstanceWithChan(request *RenameManagedInstanceRequest) (<-chan *RenameManagedInstanceResponse, <-chan error) {
	responseChan := make(chan *RenameManagedInstanceResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.RenameManagedInstance(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// RenameManagedInstanceWithCallback invokes the ecs.RenameManagedInstance API asynchronously
func (client *Client) RenameManagedInstanceWithCallback(request *RenameManagedInstanceRequest, callback func(response *RenameManagedInstanceResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *RenameManagedInstanceResponse
		var err error
		defer close(result)
		response, err = client.RenameManagedInstance(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// RenameManagedInstanceRequest is the request struct for api RenameManagedInstance
type RenameManagedInstanceRequest struct {
	*requests.RpcRequest
	ResourceOwnerId      requests.Integer `position:"Query" name:"ResourceOwnerId"`
	ResourceOwnerAccount string           `position:"Query" name:"ResourceOwnerAccount"`
	OwnerAccount         string           `position:"Query" name:"OwnerAccount"`
	OwnerId              requests.Integer `position:"Query" name:"OwnerId"`
	InstanceId           string           `position:"Query" name:"InstanceId"`
	InstanceName         string           `position:"Query" name:"InstanceName"`
}

// RenameManagedInstanceResponse is the response struct for api RenameManagedInstance
type RenameManagedInstanceResponse struct {
	*responses.BaseResponse
	RequestId    string `json:"RequestId" xml:"RequestId"`
	InstanceName string `json:"InstanceName" xml:"InstanceName"`
}

// CreateRenameManagedInstanceRequest creates a request to invoke RenameManagedInstance API
func CreateRenameManagedInstanceRequest() (request *RenameManagedInstanceRequest) {
	request = &RenameManagedInstanceRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("Ecs", "2014-05-26", "RenameManagedInstance", "ecs", "openAPI")
	request.Method = requests.POST
	return
}

// CreateRenameManagedInstanceResponse creates a response to parse from RenameManagedInstance response
func CreateRenameManagedInstanceResponse() (response *RenameManagedInstanceResponse) {
	response = &RenameManagedInstanceResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
