
package ecs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// ResetDisk_GatedLaunch invokes the ecs.ResetDisk_GatedLaunch API synchronously
// api document: https://help.aliyun.com/api/ecs/resetdisk_gatedlaunch.html
func (client *Client) ResetDisk_GatedLaunch(request *ResetDisk_GatedLaunchRequest) (response *ResetDisk_GatedLaunchResponse, err error) {
response = CreateResetDisk_GatedLaunchResponse()
err = client.DoAction(request, response)
return
}

// ResetDisk_GatedLaunchWithChan invokes the ecs.ResetDisk_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/resetdisk_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) ResetDisk_GatedLaunchWithChan(request *ResetDisk_GatedLaunchRequest) (<-chan *ResetDisk_GatedLaunchResponse, <-chan error) {
responseChan := make(chan *ResetDisk_GatedLaunchResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.ResetDisk_GatedLaunch(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// ResetDisk_GatedLaunchWithCallback invokes the ecs.ResetDisk_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/resetdisk_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) ResetDisk_GatedLaunchWithCallback(request *ResetDisk_GatedLaunchRequest, callback func(response *ResetDisk_GatedLaunchResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *ResetDisk_GatedLaunchResponse
var err error
defer close(result)
response, err = client.ResetDisk_GatedLaunch(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// ResetDisk_GatedLaunchRequest is the request struct for api ResetDisk_GatedLaunch
type ResetDisk_GatedLaunchRequest struct {
*requests.RpcRequest
                    ResourceOwnerId     requests.Integer `position:"Query" name:"ResourceOwnerId"`
                    SnapshotId     string `position:"Query" name:"SnapshotId"`
                    DiskId     string `position:"Query" name:"DiskId"`
                    ResourceOwnerAccount     string `position:"Query" name:"ResourceOwnerAccount"`
                    OwnerAccount     string `position:"Query" name:"OwnerAccount"`
                    OwnerId     requests.Integer `position:"Query" name:"OwnerId"`
}


// ResetDisk_GatedLaunchResponse is the response struct for api ResetDisk_GatedLaunch
type ResetDisk_GatedLaunchResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
}

// CreateResetDisk_GatedLaunchRequest creates a request to invoke ResetDisk_GatedLaunch API
func CreateResetDisk_GatedLaunchRequest() (request *ResetDisk_GatedLaunchRequest) {
request = &ResetDisk_GatedLaunchRequest{
RpcRequest: &requests.RpcRequest{},
}
request.InitWithApiInfo("Ecs", "2014-05-26", "ResetDisk_GatedLaunch", "", "")
return
}

// CreateResetDisk_GatedLaunchResponse creates a response to parse from ResetDisk_GatedLaunch response
func CreateResetDisk_GatedLaunchResponse() (response *ResetDisk_GatedLaunchResponse) {
response = &ResetDisk_GatedLaunchResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


