
package ecs

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// RollbackVolume_GatedLaunch invokes the ecs.RollbackVolume_GatedLaunch API synchronously
// api document: https://help.aliyun.com/api/ecs/rollbackvolume_gatedlaunch.html
func (client *Client) RollbackVolume_GatedLaunch(request *RollbackVolume_GatedLaunchRequest) (response *RollbackVolume_GatedLaunchResponse, err error) {
response = CreateRollbackVolume_GatedLaunchResponse()
err = client.DoAction(request, response)
return
}

// RollbackVolume_GatedLaunchWithChan invokes the ecs.RollbackVolume_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/rollbackvolume_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) RollbackVolume_GatedLaunchWithChan(request *RollbackVolume_GatedLaunchRequest) (<-chan *RollbackVolume_GatedLaunchResponse, <-chan error) {
responseChan := make(chan *RollbackVolume_GatedLaunchResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.RollbackVolume_GatedLaunch(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// RollbackVolume_GatedLaunchWithCallback invokes the ecs.RollbackVolume_GatedLaunch API asynchronously
// api document: https://help.aliyun.com/api/ecs/rollbackvolume_gatedlaunch.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) RollbackVolume_GatedLaunchWithCallback(request *RollbackVolume_GatedLaunchRequest, callback func(response *RollbackVolume_GatedLaunchResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *RollbackVolume_GatedLaunchResponse
var err error
defer close(result)
response, err = client.RollbackVolume_GatedLaunch(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// RollbackVolume_GatedLaunchRequest is the request struct for api RollbackVolume_GatedLaunch
type RollbackVolume_GatedLaunchRequest struct {
*requests.RpcRequest
                    ResourceOwnerId     requests.Integer `position:"Query" name:"ResourceOwnerId"`
                    SnapshotId     string `position:"Query" name:"SnapshotId"`
                    ResourceOwnerAccount     string `position:"Query" name:"ResourceOwnerAccount"`
                    OwnerAccount     string `position:"Query" name:"OwnerAccount"`
                    OwnerId     requests.Integer `position:"Query" name:"OwnerId"`
                    VolumeId     string `position:"Query" name:"VolumeId"`
}


// RollbackVolume_GatedLaunchResponse is the response struct for api RollbackVolume_GatedLaunch
type RollbackVolume_GatedLaunchResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
}

// CreateRollbackVolume_GatedLaunchRequest creates a request to invoke RollbackVolume_GatedLaunch API
func CreateRollbackVolume_GatedLaunchRequest() (request *RollbackVolume_GatedLaunchRequest) {
request = &RollbackVolume_GatedLaunchRequest{
RpcRequest: &requests.RpcRequest{},
}
request.InitWithApiInfo("Ecs", "2014-05-26", "RollbackVolume_GatedLaunch", "ecs", "openAPI")
return
}

// CreateRollbackVolume_GatedLaunchResponse creates a response to parse from RollbackVolume_GatedLaunch response
func CreateRollbackVolume_GatedLaunchResponse() (response *RollbackVolume_GatedLaunchResponse) {
response = &RollbackVolume_GatedLaunchResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


