
package aas

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// GetAccountKinshipInfoByPK invokes the aas.GetAccountKinshipInfoByPK API synchronously
// api document: https://help.aliyun.com/api/aas/getaccountkinshipinfobypk.html
func (client *Client) GetAccountKinshipInfoByPK(request *GetAccountKinshipInfoByPKRequest) (response *GetAccountKinshipInfoByPKResponse, err error) {
response = CreateGetAccountKinshipInfoByPKResponse()
err = client.DoAction(request, response)
return
}

// GetAccountKinshipInfoByPKWithChan invokes the aas.GetAccountKinshipInfoByPK API asynchronously
// api document: https://help.aliyun.com/api/aas/getaccountkinshipinfobypk.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) GetAccountKinshipInfoByPKWithChan(request *GetAccountKinshipInfoByPKRequest) (<-chan *GetAccountKinshipInfoByPKResponse, <-chan error) {
responseChan := make(chan *GetAccountKinshipInfoByPKResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.GetAccountKinshipInfoByPK(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// GetAccountKinshipInfoByPKWithCallback invokes the aas.GetAccountKinshipInfoByPK API asynchronously
// api document: https://help.aliyun.com/api/aas/getaccountkinshipinfobypk.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) GetAccountKinshipInfoByPKWithCallback(request *GetAccountKinshipInfoByPKRequest, callback func(response *GetAccountKinshipInfoByPKResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *GetAccountKinshipInfoByPKResponse
var err error
defer close(result)
response, err = client.GetAccountKinshipInfoByPK(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// GetAccountKinshipInfoByPKRequest is the request struct for api GetAccountKinshipInfoByPK
type GetAccountKinshipInfoByPKRequest struct {
*requests.RpcRequest
                    PK     string `position:"Query" name:"PK"`
}


// GetAccountKinshipInfoByPKResponse is the response struct for api GetAccountKinshipInfoByPK
type GetAccountKinshipInfoByPKResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
            PK     string `json:"PK" xml:"PK"`
            ParentPk     string `json:"ParentPk" xml:"ParentPk"`
            PartnerPk     string `json:"PartnerPk" xml:"PartnerPk"`
            AccountStructure     string `json:"AccountStructure" xml:"AccountStructure"`
            AccountName     string `json:"AccountName" xml:"AccountName"`
            IsSubAccount     bool `json:"IsSubAccount" xml:"IsSubAccount"`
}

// CreateGetAccountKinshipInfoByPKRequest creates a request to invoke GetAccountKinshipInfoByPK API
func CreateGetAccountKinshipInfoByPKRequest() (request *GetAccountKinshipInfoByPKRequest) {
request = &GetAccountKinshipInfoByPKRequest{
RpcRequest: &requests.RpcRequest{},
}
request.InitWithApiInfo("Aas", "2015-07-01", "GetAccountKinshipInfoByPK", "", "")
return
}

// CreateGetAccountKinshipInfoByPKResponse creates a response to parse from GetAccountKinshipInfoByPK response
func CreateGetAccountKinshipInfoByPKResponse() (response *GetAccountKinshipInfoByPKResponse) {
response = &GetAccountKinshipInfoByPKResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


