package aas

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// GetAccountKinShipInfoByPK invokes the aas.GetAccountKinShipInfoByPK API synchronously
// api document: https://help.aliyun.com/api/aas/getaccountkinshipinfobypk.html
func (client *Client) GetAccountKinShipInfoByPK(request *GetAccountKinShipInfoByPKRequest) (response *GetAccountKinShipInfoByPKResponse, err error) {
	response = CreateGetAccountKinShipInfoByPKResponse()
	err = client.DoAction(request, response)
	return
}

// GetAccountKinShipInfoByPKWithChan invokes the aas.GetAccountKinShipInfoByPK API asynchronously
// api document: https://help.aliyun.com/api/aas/getaccountkinshipinfobypk.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) GetAccountKinShipInfoByPKWithChan(request *GetAccountKinShipInfoByPKRequest) (<-chan *GetAccountKinShipInfoByPKResponse, <-chan error) {
	responseChan := make(chan *GetAccountKinShipInfoByPKResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.GetAccountKinShipInfoByPK(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// GetAccountKinShipInfoByPKWithCallback invokes the aas.GetAccountKinShipInfoByPK API asynchronously
// api document: https://help.aliyun.com/api/aas/getaccountkinshipinfobypk.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) GetAccountKinShipInfoByPKWithCallback(request *GetAccountKinShipInfoByPKRequest, callback func(response *GetAccountKinShipInfoByPKResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *GetAccountKinShipInfoByPKResponse
		var err error
		defer close(result)
		response, err = client.GetAccountKinShipInfoByPK(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// GetAccountKinShipInfoByPKRequest is the request struct for api GetAccountKinShipInfoByPK
type GetAccountKinShipInfoByPKRequest struct {
	*requests.RpcRequest
	PK string `position:"Query" name:"PK"`
}

// GetAccountKinShipInfoByPKResponse is the response struct for api GetAccountKinShipInfoByPK
type GetAccountKinShipInfoByPKResponse struct {
	*responses.BaseResponse
	RequestId        string `json:"RequestId" xml:"RequestId"`
	PK               string `json:"PK" xml:"PK"`
	ParentPk         string `json:"ParentPk" xml:"ParentPk"`
	PartnerPk        string `json:"PartnerPk" xml:"PartnerPk"`
	AccountStructure string `json:"AccountStructure" xml:"AccountStructure"`
	AccountName      string `json:"AccountName" xml:"AccountName"`
	IsSubAccount     bool   `json:"IsSubAccount" xml:"IsSubAccount"`
}

// CreateGetAccountKinShipInfoByPKRequest creates a request to invoke GetAccountKinShipInfoByPK API
func CreateGetAccountKinShipInfoByPKRequest() (request *GetAccountKinShipInfoByPKRequest) {
	request = &GetAccountKinShipInfoByPKRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("Aas", "2015-07-01", "GetAccountKinShipInfoByPK", "aas", "openAPI")
	return
}

// CreateGetAccountKinShipInfoByPKResponse creates a response to parse from GetAccountKinShipInfoByPK response
func CreateGetAccountKinShipInfoByPKResponse() (response *GetAccountKinShipInfoByPKResponse) {
	response = &GetAccountKinShipInfoByPKResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
