package slb

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// DescribeDomainWafWhiteList invokes the slb.DescribeDomainWafWhiteList API synchronously
// api document: https://help.aliyun.com/api/slb/describedomainwafwhitelist.html
func (client *Client) DescribeDomainWafWhiteList(request *DescribeDomainWafWhiteListRequest) (response *DescribeDomainWafWhiteListResponse, err error) {
	response = CreateDescribeDomainWafWhiteListResponse()
	err = client.DoAction(request, response)
	return
}

// DescribeDomainWafWhiteListWithChan invokes the slb.DescribeDomainWafWhiteList API asynchronously
// api document: https://help.aliyun.com/api/slb/describedomainwafwhitelist.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) DescribeDomainWafWhiteListWithChan(request *DescribeDomainWafWhiteListRequest) (<-chan *DescribeDomainWafWhiteListResponse, <-chan error) {
	responseChan := make(chan *DescribeDomainWafWhiteListResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.DescribeDomainWafWhiteList(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// DescribeDomainWafWhiteListWithCallback invokes the slb.DescribeDomainWafWhiteList API asynchronously
// api document: https://help.aliyun.com/api/slb/describedomainwafwhitelist.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) DescribeDomainWafWhiteListWithCallback(request *DescribeDomainWafWhiteListRequest, callback func(response *DescribeDomainWafWhiteListResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *DescribeDomainWafWhiteListResponse
		var err error
		defer close(result)
		response, err = client.DescribeDomainWafWhiteList(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// DescribeDomainWafWhiteListRequest is the request struct for api DescribeDomainWafWhiteList
type DescribeDomainWafWhiteListRequest struct {
	*requests.RpcRequest
	AccessKeyId          string           `position:"Query" name:"access_key_id"`
	ResourceOwnerId      requests.Integer `position:"Query" name:"ResourceOwnerId"`
	ResourceOwnerAccount string           `position:"Query" name:"ResourceOwnerAccount"`
	OwnerAccount         string           `position:"Query" name:"OwnerAccount"`
	DomainName           string           `position:"Query" name:"DomainName"`
	OwnerId              requests.Integer `position:"Query" name:"OwnerId"`
}

// DescribeDomainWafWhiteListResponse is the response struct for api DescribeDomainWafWhiteList
type DescribeDomainWafWhiteListResponse struct {
	*responses.BaseResponse
	RequestId    string                                   `json:"RequestId" xml:"RequestId"`
	WafWhiteList WafWhiteListInDescribeDomainWafWhiteList `json:"WafWhiteList" xml:"WafWhiteList"`
}

// CreateDescribeDomainWafWhiteListRequest creates a request to invoke DescribeDomainWafWhiteList API
func CreateDescribeDomainWafWhiteListRequest() (request *DescribeDomainWafWhiteListRequest) {
	request = &DescribeDomainWafWhiteListRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("Slb", "2014-05-15", "DescribeDomainWafWhiteList", "slb", "openAPI")
	return
}

// CreateDescribeDomainWafWhiteListResponse creates a response to parse from DescribeDomainWafWhiteList response
func CreateDescribeDomainWafWhiteListResponse() (response *DescribeDomainWafWhiteListResponse) {
	response = &DescribeDomainWafWhiteListResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
