package slb

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// DescribeRealtimeLogs invokes the slb.DescribeRealtimeLogs API synchronously
// api document: https://help.aliyun.com/api/slb/describerealtimelogs.html
func (client *Client) DescribeRealtimeLogs(request *DescribeRealtimeLogsRequest) (response *DescribeRealtimeLogsResponse, err error) {
	response = CreateDescribeRealtimeLogsResponse()
	err = client.DoAction(request, response)
	return
}

// DescribeRealtimeLogsWithChan invokes the slb.DescribeRealtimeLogs API asynchronously
// api document: https://help.aliyun.com/api/slb/describerealtimelogs.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) DescribeRealtimeLogsWithChan(request *DescribeRealtimeLogsRequest) (<-chan *DescribeRealtimeLogsResponse, <-chan error) {
	responseChan := make(chan *DescribeRealtimeLogsResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.DescribeRealtimeLogs(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// DescribeRealtimeLogsWithCallback invokes the slb.DescribeRealtimeLogs API asynchronously
// api document: https://help.aliyun.com/api/slb/describerealtimelogs.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) DescribeRealtimeLogsWithCallback(request *DescribeRealtimeLogsRequest, callback func(response *DescribeRealtimeLogsResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *DescribeRealtimeLogsResponse
		var err error
		defer close(result)
		response, err = client.DescribeRealtimeLogs(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// DescribeRealtimeLogsRequest is the request struct for api DescribeRealtimeLogs
type DescribeRealtimeLogsRequest struct {
	*requests.RpcRequest
	AccessKeyId          string           `position:"Query" name:"access_key_id"`
	LogStartTime         string           `position:"Query" name:"LogStartTime"`
	ResourceOwnerId      requests.Integer `position:"Query" name:"ResourceOwnerId"`
	ResourceOwnerAccount string           `position:"Query" name:"ResourceOwnerAccount"`
	LogEndTime           string           `position:"Query" name:"LogEndTime"`
	OwnerAccount         string           `position:"Query" name:"OwnerAccount"`
	OwnerId              requests.Integer `position:"Query" name:"OwnerId"`
	PageNumber           requests.Integer `position:"Query" name:"PageNumber"`
	Tags                 string           `position:"Query" name:"Tags"`
	LogType              string           `position:"Query" name:"LogType"`
	LoadBalancerId       string           `position:"Query" name:"LoadBalancerId"`
	PageSize             requests.Integer `position:"Query" name:"PageSize"`
}

// DescribeRealtimeLogsResponse is the response struct for api DescribeRealtimeLogs
type DescribeRealtimeLogsResponse struct {
	*responses.BaseResponse
	RequestId         string            `json:"RequestId" xml:"RequestId"`
	PageNumber        int               `json:"PageNumber" xml:"PageNumber"`
	PageSize          int               `json:"PageSize" xml:"PageSize"`
	TotalCount        int               `json:"TotalCount" xml:"TotalCount"`
	LBRealTimeLogsSet LBRealTimeLogsSet `json:"LBRealTimeLogsSet" xml:"LBRealTimeLogsSet"`
}

// CreateDescribeRealtimeLogsRequest creates a request to invoke DescribeRealtimeLogs API
func CreateDescribeRealtimeLogsRequest() (request *DescribeRealtimeLogsRequest) {
	request = &DescribeRealtimeLogsRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("Slb", "2014-05-15", "DescribeRealtimeLogs", "slb", "openAPI")
	return
}

// CreateDescribeRealtimeLogsResponse creates a response to parse from DescribeRealtimeLogs response
func CreateDescribeRealtimeLogsResponse() (response *DescribeRealtimeLogsResponse) {
	response = &DescribeRealtimeLogsResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
