package slb

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// RemoveDomainCcBlackList invokes the slb.RemoveDomainCcBlackList API synchronously
// api document: https://help.aliyun.com/api/slb/removedomainccblacklist.html
func (client *Client) RemoveDomainCcBlackList(request *RemoveDomainCcBlackListRequest) (response *RemoveDomainCcBlackListResponse, err error) {
	response = CreateRemoveDomainCcBlackListResponse()
	err = client.DoAction(request, response)
	return
}

// RemoveDomainCcBlackListWithChan invokes the slb.RemoveDomainCcBlackList API asynchronously
// api document: https://help.aliyun.com/api/slb/removedomainccblacklist.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) RemoveDomainCcBlackListWithChan(request *RemoveDomainCcBlackListRequest) (<-chan *RemoveDomainCcBlackListResponse, <-chan error) {
	responseChan := make(chan *RemoveDomainCcBlackListResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.RemoveDomainCcBlackList(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// RemoveDomainCcBlackListWithCallback invokes the slb.RemoveDomainCcBlackList API asynchronously
// api document: https://help.aliyun.com/api/slb/removedomainccblacklist.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) RemoveDomainCcBlackListWithCallback(request *RemoveDomainCcBlackListRequest, callback func(response *RemoveDomainCcBlackListResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *RemoveDomainCcBlackListResponse
		var err error
		defer close(result)
		response, err = client.RemoveDomainCcBlackList(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// RemoveDomainCcBlackListRequest is the request struct for api RemoveDomainCcBlackList
type RemoveDomainCcBlackListRequest struct {
	*requests.RpcRequest
	AccessKeyId          string           `position:"Query" name:"access_key_id"`
	ResourceOwnerId      requests.Integer `position:"Query" name:"ResourceOwnerId"`
	ResourceOwnerAccount string           `position:"Query" name:"ResourceOwnerAccount"`
	OwnerAccount         string           `position:"Query" name:"OwnerAccount"`
	DomainName           string           `position:"Query" name:"DomainName"`
	OwnerId              requests.Integer `position:"Query" name:"OwnerId"`
	List                 string           `position:"Query" name:"List"`
}

// RemoveDomainCcBlackListResponse is the response struct for api RemoveDomainCcBlackList
type RemoveDomainCcBlackListResponse struct {
	*responses.BaseResponse
	RequestId string `json:"RequestId" xml:"RequestId"`
}

// CreateRemoveDomainCcBlackListRequest creates a request to invoke RemoveDomainCcBlackList API
func CreateRemoveDomainCcBlackListRequest() (request *RemoveDomainCcBlackListRequest) {
	request = &RemoveDomainCcBlackListRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("Slb", "2014-05-15", "RemoveDomainCcBlackList", "slb", "openAPI")
	return
}

// CreateRemoveDomainCcBlackListResponse creates a response to parse from RemoveDomainCcBlackList response
func CreateRemoveDomainCcBlackListResponse() (response *RemoveDomainCcBlackListResponse) {
	response = &RemoveDomainCcBlackListResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
