package slb

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// SetProtectedDomainStatus invokes the slb.SetProtectedDomainStatus API synchronously
// api document: https://help.aliyun.com/api/slb/setprotecteddomainstatus.html
func (client *Client) SetProtectedDomainStatus(request *SetProtectedDomainStatusRequest) (response *SetProtectedDomainStatusResponse, err error) {
	response = CreateSetProtectedDomainStatusResponse()
	err = client.DoAction(request, response)
	return
}

// SetProtectedDomainStatusWithChan invokes the slb.SetProtectedDomainStatus API asynchronously
// api document: https://help.aliyun.com/api/slb/setprotecteddomainstatus.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) SetProtectedDomainStatusWithChan(request *SetProtectedDomainStatusRequest) (<-chan *SetProtectedDomainStatusResponse, <-chan error) {
	responseChan := make(chan *SetProtectedDomainStatusResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.SetProtectedDomainStatus(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// SetProtectedDomainStatusWithCallback invokes the slb.SetProtectedDomainStatus API asynchronously
// api document: https://help.aliyun.com/api/slb/setprotecteddomainstatus.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) SetProtectedDomainStatusWithCallback(request *SetProtectedDomainStatusRequest, callback func(response *SetProtectedDomainStatusResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *SetProtectedDomainStatusResponse
		var err error
		defer close(result)
		response, err = client.SetProtectedDomainStatus(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// SetProtectedDomainStatusRequest is the request struct for api SetProtectedDomainStatus
type SetProtectedDomainStatusRequest struct {
	*requests.RpcRequest
	AccessKeyId          string           `position:"Query" name:"access_key_id"`
	ResourceOwnerId      requests.Integer `position:"Query" name:"ResourceOwnerId"`
	ResourceOwnerAccount string           `position:"Query" name:"ResourceOwnerAccount"`
	WafStatus            string           `position:"Query" name:"WafStatus"`
	OwnerAccount         string           `position:"Query" name:"OwnerAccount"`
	DomainName           string           `position:"Query" name:"DomainName"`
	CcStatus             string           `position:"Query" name:"CcStatus"`
	OwnerId              requests.Integer `position:"Query" name:"OwnerId"`
}

// SetProtectedDomainStatusResponse is the response struct for api SetProtectedDomainStatus
type SetProtectedDomainStatusResponse struct {
	*responses.BaseResponse
	RequestId string `json:"RequestId" xml:"RequestId"`
}

// CreateSetProtectedDomainStatusRequest creates a request to invoke SetProtectedDomainStatus API
func CreateSetProtectedDomainStatusRequest() (request *SetProtectedDomainStatusRequest) {
	request = &SetProtectedDomainStatusRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("Slb", "2014-05-15", "SetProtectedDomainStatus", "slb", "openAPI")
	return
}

// CreateSetProtectedDomainStatusResponse creates a response to parse from SetProtectedDomainStatus response
func CreateSetProtectedDomainStatusResponse() (response *SetProtectedDomainStatusResponse) {
	response = &SetProtectedDomainStatusResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
