
package r_kvstore

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// DescribeConnectionDomain invokes the r_kvstore.DescribeConnectionDomain API synchronously
// api document: https://help.aliyun.com/api/r-kvstore/describeconnectiondomain.html
func (client *Client) DescribeConnectionDomain(request *DescribeConnectionDomainRequest) (response *DescribeConnectionDomainResponse, err error) {
response = CreateDescribeConnectionDomainResponse()
err = client.DoAction(request, response)
return
}

// DescribeConnectionDomainWithChan invokes the r_kvstore.DescribeConnectionDomain API asynchronously
// api document: https://help.aliyun.com/api/r-kvstore/describeconnectiondomain.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) DescribeConnectionDomainWithChan(request *DescribeConnectionDomainRequest) (<-chan *DescribeConnectionDomainResponse, <-chan error) {
responseChan := make(chan *DescribeConnectionDomainResponse, 1)
errChan := make(chan error, 1)
err := client.AddAsyncTask(func() {
defer close(responseChan)
defer close(errChan)
response, err :=  client.DescribeConnectionDomain(request)
if err != nil {
errChan <- err
} else {
responseChan <- response
}
})
if err != nil {
errChan <- err
close(responseChan)
close(errChan)
}
return responseChan, errChan
}

// DescribeConnectionDomainWithCallback invokes the r_kvstore.DescribeConnectionDomain API asynchronously
// api document: https://help.aliyun.com/api/r-kvstore/describeconnectiondomain.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) DescribeConnectionDomainWithCallback(request *DescribeConnectionDomainRequest, callback func(response *DescribeConnectionDomainResponse, err error)) (<-chan int) {
result := make(chan int, 1)
err := client.AddAsyncTask(func() {
var response *DescribeConnectionDomainResponse
var err error
defer close(result)
response, err = client.DescribeConnectionDomain(request)
callback(response, err)
result <- 1
})
if err != nil {
defer close(result)
callback(nil, err)
result <- 0
}
return result
}

// DescribeConnectionDomainRequest is the request struct for api DescribeConnectionDomain
type DescribeConnectionDomainRequest struct {
*requests.RpcRequest
                    ResourceOwnerId     requests.Integer `position:"Query" name:"ResourceOwnerId"`
                    SecurityToken     string `position:"Query" name:"SecurityToken"`
                    ResourceOwnerAccount     string `position:"Query" name:"ResourceOwnerAccount"`
                    OwnerAccount     string `position:"Query" name:"OwnerAccount"`
                    ConnectionDomain     string `position:"Query" name:"ConnectionDomain"`
                    OwnerId     requests.Integer `position:"Query" name:"OwnerId"`
}


// DescribeConnectionDomainResponse is the response struct for api DescribeConnectionDomain
type DescribeConnectionDomainResponse struct {
*responses.BaseResponse
            RequestId     string `json:"RequestId" xml:"RequestId"`
            InstanceId     string `json:"InstanceId" xml:"InstanceId"`
}

// CreateDescribeConnectionDomainRequest creates a request to invoke DescribeConnectionDomain API
func CreateDescribeConnectionDomainRequest() (request *DescribeConnectionDomainRequest) {
request = &DescribeConnectionDomainRequest{
RpcRequest: &requests.RpcRequest{},
}
request.InitWithApiInfo("R-kvstore", "2015-01-01", "DescribeConnectionDomain", "kvstore", "openAPI")
return
}

// CreateDescribeConnectionDomainResponse creates a response to parse from DescribeConnectionDomain response
func CreateDescribeConnectionDomainResponse() (response *DescribeConnectionDomainResponse) {
response = &DescribeConnectionDomainResponse{
BaseResponse: &responses.BaseResponse{},
}
return
}


