package cloudapi

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// DescribeApisBySecurityControl invokes the cloudapi.DescribeApisBySecurityControl API synchronously
// api document: https://help.aliyun.com/api/cloudapi/describeapisbysecuritycontrol.html
func (client *Client) DescribeApisBySecurityControl(request *DescribeApisBySecurityControlRequest) (response *DescribeApisBySecurityControlResponse, err error) {
	response = CreateDescribeApisBySecurityControlResponse()
	err = client.DoAction(request, response)
	return
}

// DescribeApisBySecurityControlWithChan invokes the cloudapi.DescribeApisBySecurityControl API asynchronously
// api document: https://help.aliyun.com/api/cloudapi/describeapisbysecuritycontrol.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) DescribeApisBySecurityControlWithChan(request *DescribeApisBySecurityControlRequest) (<-chan *DescribeApisBySecurityControlResponse, <-chan error) {
	responseChan := make(chan *DescribeApisBySecurityControlResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.DescribeApisBySecurityControl(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// DescribeApisBySecurityControlWithCallback invokes the cloudapi.DescribeApisBySecurityControl API asynchronously
// api document: https://help.aliyun.com/api/cloudapi/describeapisbysecuritycontrol.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) DescribeApisBySecurityControlWithCallback(request *DescribeApisBySecurityControlRequest, callback func(response *DescribeApisBySecurityControlResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *DescribeApisBySecurityControlResponse
		var err error
		defer close(result)
		response, err = client.DescribeApisBySecurityControl(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// DescribeApisBySecurityControlRequest is the request struct for api DescribeApisBySecurityControl
type DescribeApisBySecurityControlRequest struct {
	*requests.RpcRequest
	PageSize          requests.Integer `position:"Query" name:"PageSize"`
	SecurityControlId string           `position:"Query" name:"SecurityControlId"`
	PageNumber        requests.Integer `position:"Query" name:"PageNumber"`
}

// DescribeApisBySecurityControlResponse is the response struct for api DescribeApisBySecurityControl
type DescribeApisBySecurityControlResponse struct {
	*responses.BaseResponse
	RequestId  string                                  `json:"RequestId" xml:"RequestId"`
	TotalCount int                                     `json:"TotalCount" xml:"TotalCount"`
	PageSize   int                                     `json:"PageSize" xml:"PageSize"`
	PageNumber int                                     `json:"PageNumber" xml:"PageNumber"`
	ApiInfos   ApiInfosInDescribeApisBySecurityControl `json:"ApiInfos" xml:"ApiInfos"`
}

// CreateDescribeApisBySecurityControlRequest creates a request to invoke DescribeApisBySecurityControl API
func CreateDescribeApisBySecurityControlRequest() (request *DescribeApisBySecurityControlRequest) {
	request = &DescribeApisBySecurityControlRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("CloudAPI", "2016-07-14", "DescribeApisBySecurityControl", "apigateway", "openAPI")
	return
}

// CreateDescribeApisBySecurityControlResponse creates a response to parse from DescribeApisBySecurityControl response
func CreateDescribeApisBySecurityControlResponse() (response *DescribeApisBySecurityControlResponse) {
	response = &DescribeApisBySecurityControlResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
