package ft

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// BatchAuditTest02 invokes the ft.BatchAuditTest02 API synchronously
// api document: https://help.aliyun.com/api/ft/batchaudittest02.html
func (client *Client) BatchAuditTest02(request *BatchAuditTest02Request) (response *BatchAuditTest02Response, err error) {
	response = CreateBatchAuditTest02Response()
	err = client.DoAction(request, response)
	return
}

// BatchAuditTest02WithChan invokes the ft.BatchAuditTest02 API asynchronously
// api document: https://help.aliyun.com/api/ft/batchaudittest02.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) BatchAuditTest02WithChan(request *BatchAuditTest02Request) (<-chan *BatchAuditTest02Response, <-chan error) {
	responseChan := make(chan *BatchAuditTest02Response, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.BatchAuditTest02(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// BatchAuditTest02WithCallback invokes the ft.BatchAuditTest02 API asynchronously
// api document: https://help.aliyun.com/api/ft/batchaudittest02.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) BatchAuditTest02WithCallback(request *BatchAuditTest02Request, callback func(response *BatchAuditTest02Response, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *BatchAuditTest02Response
		var err error
		defer close(result)
		response, err = client.BatchAuditTest02(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// BatchAuditTest02Request is the request struct for api BatchAuditTest02
type BatchAuditTest02Request struct {
	*requests.RpcRequest
	Name             string `position:"Query" name:"Name"`
	BatchAuditTest01 string `position:"Query" name:"BatchAuditTest01"`
}

// BatchAuditTest02Response is the response struct for api BatchAuditTest02
type BatchAuditTest02Response struct {
	*responses.BaseResponse
	RequestId string `json:"RequestId" xml:"RequestId"`
	Name      string `json:"Name" xml:"Name"`
}

// CreateBatchAuditTest02Request creates a request to invoke BatchAuditTest02 API
func CreateBatchAuditTest02Request() (request *BatchAuditTest02Request) {
	request = &BatchAuditTest02Request{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("Ft", "2018-07-13", "BatchAuditTest02", "", "")
	request.Method = requests.POST
	return
}

// CreateBatchAuditTest02Response creates a response to parse from BatchAuditTest02 response
func CreateBatchAuditTest02Response() (response *BatchAuditTest02Response) {
	response = &BatchAuditTest02Response{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
