package ft

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// CountCloudProductCallTimes invokes the ft.CountCloudProductCallTimes API synchronously
// api document: https://help.aliyun.com/api/ft/countcloudproductcalltimes.html
func (client *Client) CountCloudProductCallTimes(request *CountCloudProductCallTimesRequest) (response *CountCloudProductCallTimesResponse, err error) {
	response = CreateCountCloudProductCallTimesResponse()
	err = client.DoAction(request, response)
	return
}

// CountCloudProductCallTimesWithChan invokes the ft.CountCloudProductCallTimes API asynchronously
// api document: https://help.aliyun.com/api/ft/countcloudproductcalltimes.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) CountCloudProductCallTimesWithChan(request *CountCloudProductCallTimesRequest) (<-chan *CountCloudProductCallTimesResponse, <-chan error) {
	responseChan := make(chan *CountCloudProductCallTimesResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.CountCloudProductCallTimes(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// CountCloudProductCallTimesWithCallback invokes the ft.CountCloudProductCallTimes API asynchronously
// api document: https://help.aliyun.com/api/ft/countcloudproductcalltimes.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) CountCloudProductCallTimesWithCallback(request *CountCloudProductCallTimesRequest, callback func(response *CountCloudProductCallTimesResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *CountCloudProductCallTimesResponse
		var err error
		defer close(result)
		response, err = client.CountCloudProductCallTimes(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// CountCloudProductCallTimesRequest is the request struct for api CountCloudProductCallTimes
type CountCloudProductCallTimesRequest struct {
	*requests.RpcRequest
	BucUid                  requests.Integer `position:"Query" name:"BucUid"`
	BucName                 string           `position:"Query" name:"BucName"`
	BucEmpId                string           `position:"Query" name:"BucEmpId"`
	CloudProductsJsonString string           `position:"Body" name:"CloudProductsJsonString"`
	ClearCloudCache         requests.Boolean `position:"Body" name:"ClearCloudCache"`
	ClearProductCache       requests.Boolean `position:"Body" name:"ClearProductCache"`
}

// CountCloudProductCallTimesResponse is the response struct for api CountCloudProductCallTimes
type CountCloudProductCallTimesResponse struct {
	*responses.BaseResponse
	RequestId string                 `json:"RequestId" xml:"RequestId"`
	Success   bool                   `json:"Success" xml:"Success"`
	Data      map[string]interface{} `json:"Data" xml:"Data"`
	Code      string                 `json:"Code" xml:"Code"`
	Message   string                 `json:"Message" xml:"Message"`
	MessageCN string                 `json:"MessageCN" xml:"MessageCN"`
}

// CreateCountCloudProductCallTimesRequest creates a request to invoke CountCloudProductCallTimes API
func CreateCountCloudProductCallTimesRequest() (request *CountCloudProductCallTimesRequest) {
	request = &CountCloudProductCallTimesRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("Ft", "2018-07-13", "CountCloudProductCallTimes", "", "")
	request.Method = requests.POST
	return
}

// CreateCountCloudProductCallTimesResponse creates a response to parse from CountCloudProductCallTimes response
func CreateCountCloudProductCallTimesResponse() (response *CountCloudProductCallTimesResponse) {
	response = &CountCloudProductCallTimesResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
